import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_leading_image.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_six.dart';import 'package:social_app/widgets/custom_elevated_button.dart';import 'package:social_app/widgets/custom_icon_button.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/settings_notifications_controller.dart';class SettingsNotificationsScreen extends GetWidget<SettingsNotificationsController> {const SettingsNotificationsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.onPrimaryContainer.withOpacity(1), body: SizedBox(height: 768.v, width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.topCenter, child: Container(height: 328.v, width: double.maxFinite, decoration: BoxDecoration(color: theme.colorScheme.primary))), _buildArrowLeft(), Align(alignment: Alignment.bottomCenter, child: Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 30.v), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.customBorderTL24), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [CustomImageView(imagePath: ImageConstant.imgInfoBlueGray30024x24, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 6.h, top: 2.v), child: Text("lbl_how_it_works".tr, style: CustomTextStyles.titleMediumBluegray300))]), SizedBox(height: 19.v), _buildLine(), SizedBox(height: 83.v), _buildShareViaWhatsapp(), SizedBox(height: 24.v)])))])))); } 
/// Section Widget
Widget _buildArrowLeft() { return Align(alignment: Alignment.topCenter, child: Container(padding: EdgeInsets.symmetric(vertical: 16.v), decoration: BoxDecoration(image: DecorationImage(image: AssetImage(ImageConstant.imgGroup273), fit: BoxFit.cover)), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, margin: EdgeInsets.only(left: 16.h), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleSix(text: "lbl_refer_earn".tr)), SizedBox(height: 26.v), Align(alignment: Alignment.centerLeft, child: Container(height: 131.v, width: 153.h, margin: EdgeInsets.only(left: 105.h), child: Stack(alignment: Alignment.bottomRight, children: [CustomImageView(imagePath: ImageConstant.imgGiftBox1, height: 131.adaptSize, width: 131.adaptSize, alignment: Alignment.centerRight, margin: EdgeInsets.only(right: 5.h)), CustomImageView(imagePath: ImageConstant.imgCloseOnprimarycontainer26x17, height: 26.v, width: 17.h, alignment: Alignment.bottomRight, margin: EdgeInsets.only(bottom: 39.v)), CustomImageView(imagePath: ImageConstant.imgCloseOnprimarycontainer26x17, height: 51.v, width: 34.h, alignment: Alignment.topLeft, margin: EdgeInsets.only(top: 31.v), onTap: () {onTapImgClose();})]))), SizedBox(height: 10.v), Text("msg_refer_earn_rewards".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 5.v), SizedBox(width: 261.h, child: Text("msg_share_app_name".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyMediumGray900)), SizedBox(height: 34.v)]))); } 
/// Section Widget
Widget _buildLine() { return SizedBox(height: 205.v, width: 308.h, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: SizedBox(height: 102.v, child: VerticalDivider(width: 1.h, thickness: 1.v)))), Align(alignment: Alignment.topCenter, child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min, children: [Container(width: 48.adaptSize, margin: EdgeInsets.only(bottom: 8.v), padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 11.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder23), child: Text("lbl_1".tr, style: CustomTextStyles.titleLargeMedium)), Expanded(child: Padding(padding: EdgeInsets.only(left: 15.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_share_your_link".tr, style: theme.textTheme.titleMedium), SizedBox(height: 1.v), SizedBox(width: 245.h, child: Text("msg_share_your_unique".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyMedium))])))])), Align(alignment: Alignment.centerLeft, child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: 48.adaptSize, margin: EdgeInsets.only(bottom: 9.v), padding: EdgeInsets.symmetric(horizontal: 18.h, vertical: 11.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder23), child: Text("lbl_2".tr, style: CustomTextStyles.titleLargeMedium)), Padding(padding: EdgeInsets.only(left: 15.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_friend_registers".tr, style: theme.textTheme.titleMedium), SizedBox(width: 203.h, child: Text("msg_when_your_friend".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyMedium))]))])), Align(alignment: Alignment.bottomLeft, child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: 48.adaptSize, margin: EdgeInsets.only(bottom: 6.v), padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 11.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder23), child: Text("lbl_32".tr, style: CustomTextStyles.titleLargeMedium)), Padding(padding: EdgeInsets.only(left: 15.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_first_call_bonus".tr, style: theme.textTheme.titleMedium), SizedBox(height: 1.v), SizedBox(width: 216.h, child: Text("msg_earn_tokens_when".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyMedium))]))]))])); } 
/// Section Widget
Widget _buildShareViaWhatsapp() { return Row(children: [Expanded(child: CustomElevatedButton(text: "msg_share_via_whatsapp".tr, leftIcon: Container(margin: EdgeInsets.only(right: 10.h), child: CustomImageView(imagePath: ImageConstant.imgWhatsapp1, height: 24.adaptSize, width: 24.adaptSize)))), Padding(padding: EdgeInsets.only(left: 10.h), child: CustomIconButton(height: 56.adaptSize, width: 56.adaptSize, padding: EdgeInsets.all(16.h), decoration: IconButtonStyleHelper.outlineGrayTL28, child: CustomImageView(imagePath: ImageConstant.imgSearchGray90056x56)))]); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 

/// Navigates to the previous screen.
onTapImgClose() { Get.back(); } 
 }
