import 'package:social_app/widgets/custom_text_form_field.dart';import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_title_image.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_six.dart';import 'package:social_app/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/registration_ste5_controller.dart';class RegistrationSte5Screen extends GetWidget<RegistrationSte5Controller> {const RegistrationSte5Screen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [_buildNewpassword(), _buildRegistrationStep()])), bottomNavigationBar: _buildContinue())); } 
/// Section Widget
Widget _buildInputField() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_new_password".tr, style: theme.textTheme.titleSmall), SizedBox(height: 5.v), Obx(() => CustomTextFormField(controller: controller.newpasswordController, suffix: InkWell(onTap: () {controller.isShowPassword.value = !controller.isShowPassword.value;}, child: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 15.h, 14.v), child: CustomImageView(imagePath: ImageConstant.imgEyeoff, height: 24.adaptSize, width: 24.adaptSize))), suffixConstraints: BoxConstraints(maxHeight: 52.v), obscureText: controller.isShowPassword.value))]); } 
/// Section Widget
Widget _buildInputField1() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_confirm_password".tr, style: theme.textTheme.titleSmall), SizedBox(height: 5.v), Obx(() => CustomTextFormField(controller: controller.confirmpasswordController, textInputAction: TextInputAction.done, suffix: InkWell(onTap: () {controller.isShowPassword1.value = !controller.isShowPassword1.value;}, child: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 15.h, 14.v), child: CustomImageView(imagePath: ImageConstant.imgEyeoff, height: 24.adaptSize, width: 24.adaptSize))), suffixConstraints: BoxConstraints(maxHeight: 52.v), obscureText: controller.isShowPassword1.value))]); } 
/// Section Widget
Widget _buildNewpassword() { return SizedBox(height: 357.v, width: double.maxFinite, child: Stack(alignment: Alignment.topLeft, children: [CustomImageView(imagePath: ImageConstant.imgAccent10, height: 252.v, width: 154.h, alignment: Alignment.topRight), Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 16.h, top: 90.v), child: Text("msg_create_a_password".tr, style: theme.textTheme.headlineSmall))), Align(alignment: Alignment.topCenter, child: Container(width: 333.h, margin: EdgeInsets.only(top: 127.v), child: Text("msg_set_the_new_password".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.titleSmall))), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildInputField(), SizedBox(height: 15.v), _buildInputField1()]))), CustomAppBar(height: 59.v, centerTitle: true, title: Column(children: [Padding(padding: EdgeInsets.only(left: 16.h, right: 150.h), child: Row(children: [AppbarTitleImage(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, onTap: () {onTapArrowLeft();}), AppbarSubtitleSix(text: "lbl_step_5_of_8".tr, margin: EdgeInsets.only(left: 109.h, top: 3.v))])), SizedBox(height: 16.v), SizedBox(height: 3.v, width: double.maxFinite, child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.center, child: SizedBox(width: double.maxFinite, child: Divider(color: appTheme.gray10001))), Align(alignment: Alignment.centerLeft, child: SizedBox(width: double.maxFinite, child: Divider(color: appTheme.green400, endIndent: 141.h)))]))]), styleType: Style.bgFill)])); } 
/// Section Widget
Widget _buildRegistrationStep() { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 15.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Text("msg_passwor_strength".tr, style: CustomTextStyles.titleSmallGray900), Padding(padding: EdgeInsets.only(left: 10.h), child: Text("lbl_strong".tr, style: CustomTextStyles.titleSmallGreen400))]), SizedBox(height: 9.v), Divider(color: appTheme.green400), SizedBox(height: 19.v), Text("msg_password_must_contain".tr, style: CustomTextStyles.bodyMediumGray900), SizedBox(height: 10.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgCheck, height: 18.adaptSize, width: 18.adaptSize), Padding(padding: EdgeInsets.only(left: 6.h), child: Text("msg_at_least_6_characters".tr, style: theme.textTheme.titleSmall))]), SizedBox(height: 10.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgCheck, height: 18.adaptSize, width: 18.adaptSize), Padding(padding: EdgeInsets.only(left: 6.h), child: Text("msg_at_least_one_uppercase".tr, style: theme.textTheme.titleSmall))]), SizedBox(height: 9.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgCheck, height: 18.adaptSize, width: 18.adaptSize), Padding(padding: EdgeInsets.only(left: 6.h), child: Text("msg_at_least_one_number_0_9".tr, style: theme.textTheme.titleSmall))]), SizedBox(height: 5.v)])); } 
/// Section Widget
Widget _buildContinue() { return CustomElevatedButton(text: "lbl_continue".tr, margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 54.v), onPressed: () {onTapContinue();}); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the registrationStepp6Screen when the action is triggered.
onTapContinue() { Get.toNamed(AppRoutes.registrationStepp6Screen, ); } 
 }
