import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_leading_image.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_one.dart';import 'package:social_app/widgets/app_bar/appbar_title_image.dart';import 'package:social_app/widgets/app_bar/appbar_trailing_button_one.dart';import 'package:social_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:social_app/widgets/custom_text_form_field.dart';import 'package:social_app/widgets/custom_icon_button.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/message_chat_with_user_active_controller.dart';import 'package:social_app/presentation/message_chat_with_user_default_one_dialog/message_chat_with_user_default_one_dialog.dart';import 'package:social_app/presentation/message_chat_with_user_default_one_dialog/controller/message_chat_with_user_default_one_controller.dart';class MessageChatWithUserActiveScreen extends GetWidget<MessageChatWithUserActiveController> {const MessageChatWithUserActiveScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 431.v, width: double.maxFinite, child: Stack(alignment: Alignment.topRight, children: [_buildNotMuchJustChilling(), CustomImageView(imagePath: ImageConstant.imgAccent32, height: 252.v, width: 154.h, alignment: Alignment.topRight, margin: EdgeInsets.only(top: 44.v)), _buildAppBar()])), SizedBox(height: 21.v), _buildMessage(), SizedBox(height: 5.v)])))); } 
/// Section Widget
Widget _buildNotMuchJustChilling() { return Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(margin: EdgeInsets.only(right: 126.h), padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 14.v), decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.customBorderTL20), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text("msg_not_much_just_chilling".tr, style: CustomTextStyles.bodyLargeGray900)])), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 14.h), child: _buildFrame(time: "lbl_09_32_pm".tr)), SizedBox(height: 14.v), Align(alignment: Alignment.centerRight, child: Container(margin: EdgeInsets.only(left: 116.h), padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 13.v), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.customBorderTL201), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), SizedBox(width: 193.h, child: Text("msg_same_here_anything".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyLargeGray900))]))), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 130.h), child: _buildFrame(time: "lbl_09_32_pm".tr)), SizedBox(height: 14.v), Container(width: 253.h, margin: EdgeInsets.only(right: 90.h), padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 13.v), decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.customBorderTL20), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Container(width: 195.h, margin: EdgeInsets.only(right: 27.h), child: Text("msg_nah_just_the_usual".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyLargeGray900))])), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 14.h), child: _buildFrame(time: "lbl_09_32_pm".tr)), SizedBox(height: 14.v), Align(alignment: Alignment.centerRight, child: Container(margin: EdgeInsets.only(left: 87.h), padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 13.v), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.customBorderTL201), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), SizedBox(width: 224.h, child: Text("msg_haha_i_feel_that".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyLargeGray900))]))), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 101.h), child: _buildFrame(time: "lbl_09_32_pm".tr))]))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 100.v, leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, margin: EdgeInsets.only(left: 16.h, top: 60.v, bottom: 16.v), onTap: () {onTapArrowLeft();}), title: Padding(padding: EdgeInsets.only(left: 10.h, top: 61.v, bottom: 16.v), child: Row(children: [AppbarSubtitleOne(text: "lbl_taranvir_k".tr), AppbarTitleImage(imagePath: ImageConstant.imgVerified, margin: EdgeInsets.only(left: 2.h, top: 3.v, bottom: 2.v))])), actions: [AppbarTrailingButtonOne(margin: EdgeInsets.only(left: 16.h, top: 52.v, right: 8.h)), AppbarTrailingImage(imagePath: ImageConstant.imgVideo, margin: EdgeInsets.fromLTRB(20.h, 62.v, 8.h, 10.v)), AppbarTrailingImage(imagePath: ImageConstant.imgPhoneGray900, margin: EdgeInsets.fromLTRB(20.h, 62.v, 24.h, 10.v))], styleType: Style.bgFill_3); } 
/// Section Widget
Widget _buildMessage() { return Container(decoration: AppDecoration.outlineBlack90001, child: Column(mainAxisSize: MainAxisSize.min, children: [Divider(), SizedBox(height: 6.v), Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomTextFormField(controller: controller.messageController, hintText: "msg_write_a_message".tr, hintStyle: CustomTextStyles.titleMediumBluegray300, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(15.h, 14.v, 10.h, 14.v), child: CustomImageView(imagePath: ImageConstant.imgSmile, height: 24.adaptSize, width: 24.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 52.v), contentPadding: EdgeInsets.only(top: 16.v, right: 30.h, bottom: 16.v), borderDecoration: TextFormFieldStyleHelper.outlineGrayTL26, fillColor: appTheme.gray20002)), Padding(padding: EdgeInsets.only(left: 6.h), child: CustomIconButton(height: 52.adaptSize, width: 52.adaptSize, padding: EdgeInsets.all(14.h), decoration: IconButtonStyleHelper.fillPrimaryTL24, onTap: () {onTapBtnIconButton();}, child: CustomImageView(imagePath: ImageConstant.imgIconSolidPaperAirplane)))])), SizedBox(height: 5.v)])); } 
/// Common widget
Widget _buildFrame({required String time}) { return Row(children: [Text(time, style: CustomTextStyles.bodySmallBluegray300.copyWith(color: appTheme.blueGray300)), CustomImageView(imagePath: ImageConstant.imgDoubleCheck, height: 14.adaptSize, width: 14.adaptSize, margin: EdgeInsets.only(left: 4.h))]); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 

/// Displays a dialog with the [MessageChatWithUserDefaultOneDialog] content.
onTapBtnIconButton() { Get.dialog(AlertDialog(backgroundColor: Colors.transparent, contentPadding: EdgeInsets.zero, insetPadding: const EdgeInsets.only(left: 0), content:MessageChatWithUserDefaultOneDialog(Get.put(MessageChatWithUserDefaultOneController(),),),)); } 
 }
