import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_title_searchview.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_four.dart';import 'package:social_app/widgets/custom_outlined_button.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/settings_security_privacy_block_user_controller.dart';class SettingsSecurityPrivacyBlockUserScreen extends GetWidget<SettingsSecurityPrivacyBlockUserController> {const SettingsSecurityPrivacyBlockUserScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(height: 768.v, width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgAccent76, height: 252.v, width: 154.h, alignment: Alignment.topRight), _buildBlock()])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 54.v, title: AppbarTitleSearchview(margin: EdgeInsets.only(left: 16.h), hintText: "lbl_anjali_arora".tr, controller: controller.searchController), actions: [AppbarSubtitleFour(text: "lbl_cancel".tr, margin: EdgeInsets.fromLTRB(15.h, 16.v, 16.h, 15.v), onTap: () {onTapCancel();})]); } 
/// Section Widget
Widget _buildBlock() { return Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.fromLTRB(16.h, 84.v, 16.h, 626.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgRectangle258x58, height: 58.adaptSize, width: 58.adaptSize, radius: BorderRadius.circular(29.h)), Padding(padding: EdgeInsets.only(left: 15.h, top: 6.v, bottom: 6.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_anjali_arora".tr, style: CustomTextStyles.titleMediumSemiBold), CustomImageView(imagePath: ImageConstant.imgVerified, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 2.h, bottom: 4.v))]), SizedBox(height: 3.v), Text("msg_social_media_infuencer".tr, style: theme.textTheme.bodyLarge)])), Spacer(), CustomOutlinedButton(height: 32.v, width: 64.h, text: "lbl_block".tr, margin: EdgeInsets.symmetric(vertical: 13.v), buttonTextStyle: CustomTextStyles.titleSmallGray900, onPressed: () {onTapBlock();})]))); } 
/// Navigates to the settingsSecurityPrivacyBlockedScreen when the action is triggered.
onTapCancel() { Get.toNamed(AppRoutes.settingsSecurityPrivacyBlockedScreen, ); } 
/// Navigates to the settingsSecurityPrivacyBlockedScreen when the action is triggered.
onTapBlock() { Get.toNamed(AppRoutes.settingsSecurityPrivacyBlockedScreen, ); } 
 }
