name: social_app
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.6
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.1
  outline_gradient_button: ^2.0.1+1
  country_pickers: ^2.0.0
  staggered_grid_view_flutter: ^0.0.4
  sms_autofill: ^2.3.0
  easy_date_timeline: ^1.0.2
  dotted_border: ^2.1.0
  qr_flutter: ^4.1.0
  intl: ^0.18.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: SF Pro Display
      fonts: 
        - asset: assets/fonts/SFProDisplayRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplayMedium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplayBold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplaySemibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplayLight.ttf
          weight: 300
    - family: Gilroy
      fonts: 
        - asset: assets/fonts/GilroySemiBold.ttf
          weight: 600
        - asset: assets/fonts/GilroyMedium.ttf
          weight: 500
    - family: SF Pro Text
      fonts: 
        - asset: assets/fonts/SFProTextSemibold.ttf
          weight: 600
        - asset: assets/fonts/SFProTextMedium.ttf
          weight: 500
        - asset: assets/fonts/SFProTextRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProTextLight.ttf
          weight: 300
