import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_leading_image.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_three.dart';import 'package:social_app/widgets/custom_icon_button.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/audio_call_controller.dart';class AudioCallScreen extends GetWidget<AudioCallController> {const AudioCallScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: appTheme.gray900, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 16.v), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [_buildEleven(), SizedBox(height: 10.v), _buildTwelve(), SizedBox(height: 4.v)])), bottomNavigationBar: _buildMicOffFILLW())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimarycontainer, margin: EdgeInsets.only(left: 16.h), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleThree(text: "msg_end_to_end_encrypted".tr)); } 
/// Section Widget
Widget _buildEleven() { return SizedBox(height: 288.v, width: 355.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgRectangle2288x355, height: 288.v, width: 355.h, radius: BorderRadius.circular(20.h), alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgMaskGroup60x60, height: 120.adaptSize, width: 120.adaptSize, alignment: Alignment.center)])); } 
/// Section Widget
Widget _buildTwelve() { return SizedBox(height: 288.v, width: 355.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgImage33, height: 288.v, width: 355.h, radius: BorderRadius.circular(20.h), alignment: Alignment.center), Align(alignment: Alignment.center, child: SizedBox(height: 120.adaptSize, width: 120.adaptSize, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgRectangle2120x120, height: 120.adaptSize, width: 120.adaptSize, radius: BorderRadius.circular(60.h), alignment: Alignment.center), Align(alignment: Alignment.center, child: SizedBox(height: 120.adaptSize, width: 120.adaptSize, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgRectangle3120x120, height: 120.adaptSize, width: 120.adaptSize, radius: BorderRadius.circular(60.h), alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgImage33120x120, height: 120.adaptSize, width: 120.adaptSize, radius: BorderRadius.circular(60.h), alignment: Alignment.center)])))])))])); } 
/// Section Widget
Widget _buildMicOffFILLW() { return Padding(padding: EdgeInsets.only(left: 27.h, right: 27.h, bottom: 54.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(right: 19.h), child: CustomIconButton(height: 52.adaptSize, width: 52.adaptSize, padding: EdgeInsets.all(14.h), decoration: IconButtonStyleHelper.fillOnPrimaryContainer, child: CustomImageView(imagePath: ImageConstant.imgVolumeUpFill0)))), Expanded(child: Padding(padding: EdgeInsets.symmetric(horizontal: 19.h), child: CustomIconButton(height: 52.adaptSize, width: 52.adaptSize, padding: EdgeInsets.all(16.h), decoration: IconButtonStyleHelper.fillOnPrimaryContainer, child: CustomImageView(imagePath: ImageConstant.imgVideoOnprimarycontainer)))), Expanded(child: Padding(padding: EdgeInsets.symmetric(horizontal: 19.h), child: CustomIconButton(height: 52.adaptSize, width: 52.adaptSize, padding: EdgeInsets.all(14.h), decoration: IconButtonStyleHelper.fillOnPrimaryContainer, child: CustomImageView(imagePath: ImageConstant.imgMicOffFill0W)))), Expanded(child: Padding(padding: EdgeInsets.only(left: 19.h), child: CustomIconButton(height: 52.adaptSize, width: 52.adaptSize, padding: EdgeInsets.all(12.h), decoration: IconButtonStyleHelper.fillPrimaryContainer, child: CustomImageView(imagePath: ImageConstant.imgEndCall))))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
