import 'package:social_app/widgets/custom_text_form_field.dart';import 'models/frame9_item_model.dart';import '../send_gift_bottomsheet/widgets/frame9_item_widget.dart';import 'package:social_app/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/send_gift_controller.dart';
// ignore_for_file: must_be_immutable
class SendGiftBottomsheet extends StatelessWidget {SendGiftBottomsheet(this.controller, {Key? key}) : super(key: key);

SendGiftController controller;

@override Widget build(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 8.v), decoration: AppDecoration.fillBlack.copyWith(borderRadius: BorderRadiusStyle.customBorderTL24), child: Column(mainAxisSize: MainAxisSize.min, children: [Container(height: 4.v, width: 24.h, decoration: BoxDecoration(color: theme.colorScheme.onPrimaryContainer.withOpacity(1), borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 19.v), Text("lbl_send_gift".tr, style: CustomTextStyles.titleMediumOnPrimaryContainerBold), SizedBox(height: 19.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_custom_tokens".tr, style: CustomTextStyles.titleSmallGray800)), SizedBox(height: 6.v), CustomTextFormField(controller: controller.group1000004495Controller, hintText: "lbl_20".tr, textInputAction: TextInputAction.done, contentPadding: EdgeInsets.symmetric(horizontal: 30.h, vertical: 11.v), borderDecoration: TextFormFieldStyleHelper.outlineGrayTL21, fillColor: appTheme.gray900), SizedBox(height: 15.v), Obx(() => Wrap(runSpacing: 10.v, spacing: 10.h, children: List<Widget>.generate(controller.sendGiftModelObj.value.frame9ItemList.value.length, (index) {Frame9ItemModel model = controller.sendGiftModelObj.value.frame9ItemList.value[index]; return Frame9ItemWidget(model);}))), SizedBox(height: 20.v), CustomElevatedButton(height: 46.v, text: "lbl_send".tr, buttonStyle: CustomButtonStyles.fillPrimaryTL23, onPressed: () {onTapSend();}), SizedBox(height: 46.v)])); } 
/// Navigates to the videoCallOneScreen when the action is triggered.
onTapSend() { Get.toNamed(AppRoutes.videoCallOneScreen, ); } 
 }
