import '../../../core/app_export.dart';import 'frame_item_model.dart';import 'frame1_item_model.dart';import 'frame2_item_model.dart';import 'frame3_item_model.dart';import 'frame4_item_model.dart';import 'frame5_item_model.dart';import 'frame6_item_model.dart';import 'frame7_item_model.dart';import 'frame8_item_model.dart';/// This class defines the variables used in the [home_page],
/// and is typically used to hold data that is passed between different parts of the application.
class HomeModel {Rx<List<FrameItemModel>> frameItemList = Rx([FrameItemModel(actors:ImageConstant.imgThumbsUp.obs,actors1: "Actors".obs),FrameItemModel(actors:ImageConstant.imgRunningShoe.obs,actors1: "Athletes".obs),FrameItemModel(actors:ImageConstant.imgTheater3.obs,actors1: "Comedians".obs),FrameItemModel(actors:ImageConstant.imgGuitar.obs,actors1: "Musicians".obs),FrameItemModel(actors:ImageConstant.imgMovie.obs,actors1: "Creators".obs),FrameItemModel(actors:ImageConstant.imgMenu.obs,actors1: "Doctors".obs),FrameItemModel(actors:ImageConstant.imgChefHat3.obs,actors1: "Chef".obs),FrameItemModel(actors:ImageConstant.imgGraduateHat.obs,actors1: "Teachers".obs),FrameItemModel(actors:ImageConstant.imgMagicCards.obs,actors1: "Astrologer".obs),FrameItemModel(actors:ImageConstant.imgAmericanFootball.obs,actors1: "Sports".obs)]);

Rx<List<Frame1ItemModel>> frame1ItemList = Rx([Frame1ItemModel(online: "Online".obs,fifty: "5.0".obs,anjaliArora: "Anjali Arora".obs,socialMediaInfluencer: "Social Media Influencer".obs)]);

Rx<List<Frame2ItemModel>> frame2ItemList = Rx([Frame2ItemModel(anjaliArora: "Anjali Arora".obs,socialMediaInfluencer: "Social Media Influencer".obs,online: "Online".obs,fifty: "5.0".obs,image:ImageConstant.imgRectangle2.obs)]);

Rx<List<Frame3ItemModel>> frame3ItemList = Rx([Frame3ItemModel(online:ImageConstant.imgRectangle2.obs,online1: "Online".obs,fifty: "5.0".obs,anjaliArora: "Anjali Arora".obs,socialMediaInfluencer: "Social Media Influencer".obs),Frame3ItemModel(online:ImageConstant.imgRectangle2.obs),Frame3ItemModel(online:ImageConstant.imgRectangle2.obs),Frame3ItemModel(online:ImageConstant.imgRectangle2220x156.obs,online1: "Online".obs,fifty: "5.0".obs,anjaliArora: "Priya Sangar".obs,socialMediaInfluencer: "Social Media Influencer".obs),Frame3ItemModel(online:ImageConstant.imgRectangle21.obs,online1: "Online".obs,fifty: "4.2".obs,anjaliArora: "Kamya Arora".obs,socialMediaInfluencer: "Social Media Influencer".obs),Frame3ItemModel(online:ImageConstant.imgRectangle22.obs,online1: "Online".obs,fifty: "4.5".obs,anjaliArora: "Dolphy".obs,socialMediaInfluencer: "Social Media Influencer".obs)]);

Rx<List<Frame4ItemModel>> frame4ItemList = Rx([Frame4ItemModel(online:ImageConstant.imgRectangle2.obs,online1: "Online".obs,fifty: "5.0".obs,anjaliArora: "Anjali Arora".obs,socialMediaInfluencer: "Social Media Influencer".obs),Frame4ItemModel(online:ImageConstant.imgRectangle2.obs),Frame4ItemModel(online:ImageConstant.imgRectangle2.obs),Frame4ItemModel(online:ImageConstant.imgRectangle2220x156.obs,online1: "Online".obs,fifty: "5.0".obs,anjaliArora: "Priya Sangar".obs,socialMediaInfluencer: "Social Media Influencer".obs),Frame4ItemModel(online:ImageConstant.imgRectangle21.obs,online1: "Online".obs,fifty: "4.2".obs,anjaliArora: "Kamya Arora".obs,socialMediaInfluencer: "Social Media Influencer".obs),Frame4ItemModel(online:ImageConstant.imgRectangle22.obs,online1: "Online".obs,fifty: "4.5".obs,anjaliArora: "Dolphy".obs,socialMediaInfluencer: "Social Media Influencer".obs)]);

Rx<List<Frame5ItemModel>> frame5ItemList = Rx([Frame5ItemModel(online:ImageConstant.imgRectangle2.obs,online1: "Online".obs,fifty: "5.0".obs,anjaliArora: "Anjali Arora".obs,socialMediaInfluencer: "Social Media Influencer".obs),Frame5ItemModel(online:ImageConstant.imgRectangle2.obs),Frame5ItemModel(online:ImageConstant.imgRectangle2.obs),Frame5ItemModel(online:ImageConstant.imgRectangle2220x156.obs,online1: "Online".obs,fifty: "5.0".obs,anjaliArora: "Priya Sangar".obs,socialMediaInfluencer: "Social Media Influencer".obs),Frame5ItemModel(online:ImageConstant.imgRectangle21.obs,online1: "Online".obs,fifty: "4.2".obs,anjaliArora: "Kamya Arora".obs,socialMediaInfluencer: "Social Media Influencer".obs),Frame5ItemModel(online:ImageConstant.imgRectangle22.obs,online1: "Online".obs,fifty: "4.5".obs,anjaliArora: "Dolphy".obs,socialMediaInfluencer: "Social Media Influencer".obs)]);

Rx<List<Frame6ItemModel>> frame6ItemList = Rx([Frame6ItemModel(online:ImageConstant.imgRectangle2.obs,online1: "Online".obs,fifty: "5.0".obs,anjaliArora: "Anjali Arora".obs,socialMediaInfluencer: "Social Media Influencer".obs),Frame6ItemModel(online:ImageConstant.imgRectangle2.obs),Frame6ItemModel(online:ImageConstant.imgRectangle2.obs),Frame6ItemModel(online:ImageConstant.imgRectangle2220x156.obs,online1: "Online".obs,fifty: "5.0".obs,anjaliArora: "Priya Sangar".obs,socialMediaInfluencer: "Social Media Influencer".obs),Frame6ItemModel(online:ImageConstant.imgRectangle21.obs,online1: "Online".obs,fifty: "4.2".obs,anjaliArora: "Kamya Arora".obs,socialMediaInfluencer: "Social Media Influencer".obs),Frame6ItemModel(online:ImageConstant.imgRectangle22.obs,online1: "Online".obs,fifty: "4.5".obs,anjaliArora: "Dolphy".obs,socialMediaInfluencer: "Social Media Influencer".obs)]);

Rx<List<Frame7ItemModel>> frame7ItemList = Rx([Frame7ItemModel(online:ImageConstant.imgRectangle2.obs,online1: "Online".obs,fifty: "5.0".obs,anjaliArora: "Anjali Arora".obs,socialMediaInfluencer: "Social Media Influencer".obs),Frame7ItemModel(online:ImageConstant.imgRectangle2.obs),Frame7ItemModel(online:ImageConstant.imgRectangle2.obs),Frame7ItemModel(online:ImageConstant.imgRectangle2220x156.obs,online1: "Online".obs,fifty: "5.0".obs,anjaliArora: "Priya Sangar".obs,socialMediaInfluencer: "Social Media Influencer".obs),Frame7ItemModel(online:ImageConstant.imgRectangle21.obs,online1: "Online".obs,fifty: "4.2".obs,anjaliArora: "Kamya Arora".obs,socialMediaInfluencer: "Social Media Influencer".obs),Frame7ItemModel(online:ImageConstant.imgRectangle22.obs,online1: "Online".obs,fifty: "4.5".obs,anjaliArora: "Dolphy".obs,socialMediaInfluencer: "Social Media Influencer".obs)]);

Rx<List<Frame8ItemModel>> frame8ItemList = Rx([Frame8ItemModel(online:ImageConstant.imgRectangle2.obs,online1: "Online".obs,fifty: "5.0".obs,anjaliArora: "Anjali Arora".obs,socialMediaInfluencer: "Social Media Influencer".obs),Frame8ItemModel(online:ImageConstant.imgRectangle2.obs),Frame8ItemModel(online:ImageConstant.imgRectangle2.obs),Frame8ItemModel(online:ImageConstant.imgRectangle2220x156.obs,online1: "Online".obs,fifty: "5.0".obs,anjaliArora: "Priya Sangar".obs,socialMediaInfluencer: "Social Media Influencer".obs),Frame8ItemModel(online:ImageConstant.imgRectangle21.obs,online1: "Online".obs,fifty: "4.2".obs,anjaliArora: "Kamya Arora".obs,socialMediaInfluencer: "Social Media Influencer".obs),Frame8ItemModel(online:ImageConstant.imgRectangle22.obs,online1: "Online".obs,fifty: "4.5".obs,anjaliArora: "Dolphy".obs,socialMediaInfluencer: "Social Media Influencer".obs)]);

 }
