import 'package:social_app/presentation/home_page/home_page.dart';import 'widgets/feedsactive_item_widget.dart';import 'models/feedsactive_item_model.dart';import 'package:social_app/widgets/custom_icon_button.dart';import 'package:outline_gradient_button/outline_gradient_button.dart';import 'package:social_app/widgets/custom_bottom_bar.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/feeds_active_controller.dart';class FeedsActiveScreen extends GetWidget<FeedsActiveController> {const FeedsActiveScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(height: 668.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgAccent51, height: 252.v, width: 154.h, alignment: Alignment.topRight), Align(alignment: Alignment.bottomCenter, child: Container(margin: EdgeInsets.symmetric(horizontal: 16.h), decoration: AppDecoration.outlineBlack.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Container(height: 360.v, width: 343.h, decoration: BoxDecoration(color: theme.colorScheme.onPrimaryContainer.withOpacity(1), borderRadius: BorderRadius.vertical(top: Radius.circular(20.h)))))), _buildHeart(), Align(alignment: Alignment.topLeft, child: Container(width: 293.h, margin: EdgeInsets.only(left: 32.h, top: 149.v), child: Text("msg_happy_mother_s_day".tr, maxLines: 3, overflow: TextOverflow.ellipsis, style: theme.textTheme.titleMedium))), CustomImageView(imagePath: ImageConstant.imgRectangle23250x311, height: 250.v, width: 311.h, radius: BorderRadius.circular(10.h), alignment: Alignment.center), Align(alignment: Alignment.topLeft, child: Container(height: 12.adaptSize, width: 12.adaptSize, margin: EdgeInsets.only(left: 15.h, top: 133.v), decoration: BoxDecoration(color: theme.colorScheme.onPrimaryContainer.withOpacity(1), borderRadius: BorderRadius.circular(6.h)))), _buildArrowLeft(), _buildPlay()])), bottomNavigationBar: _buildBottomBar())); } 
/// Section Widget
Widget _buildHeart() { return Align(alignment: Alignment.bottomCenter, child: Container(margin: EdgeInsets.symmetric(horizontal: 16.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 15.v), decoration: AppDecoration.fillGray10001.copyWith(borderRadius: BorderRadiusStyle.customBorderBL20), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [CustomImageView(imagePath: ImageConstant.imgNavFeeds, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 4.h, top: 3.v, bottom: 3.v), child: Text("lbl_250".tr, style: theme.textTheme.titleSmall)), CustomImageView(imagePath: ImageConstant.imgInbox2, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 10.h)), Padding(padding: EdgeInsets.only(left: 4.h, top: 3.v, bottom: 3.v), child: Text("lbl_80".tr, style: theme.textTheme.titleSmall))]), SizedBox(height: 15.v), Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 14.v);}, itemCount: controller.feedsActiveModelObj.value.feedsactiveItemList.value.length, itemBuilder: (context, index) {FeedsactiveItemModel model = controller.feedsActiveModelObj.value.feedsactiveItemList.value[index]; return FeedsactiveItemWidget(model);}))]))); } 
/// Section Widget
Widget _buildArrowLeft() { return Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.fromLTRB(16.h, 8.v, 16.h, 620.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 8.v), onTap: () {onTapImgArrowLeft();}), Padding(padding: EdgeInsets.only(left: 15.h, top: 6.v, bottom: 6.v), child: Text("lbl_feeds".tr, style: theme.textTheme.titleLarge)), Spacer(), OutlineGradientButton(padding: EdgeInsets.only(left: 1.h, top: 1.v, right: 1.h, bottom: 1.v), strokeWidth: 1.h, gradient: LinearGradient(begin: Alignment(0.09, -0.08), end: Alignment(0.75, 1.1), colors: [theme.colorScheme.onPrimaryContainer.withOpacity(1), theme.colorScheme.onPrimaryContainer.withOpacity(0), theme.colorScheme.onPrimaryContainer.withOpacity(1)]), corners: Corners(topLeft: Radius.circular(20), topRight: Radius.circular(20), bottomLeft: Radius.circular(20), bottomRight: Radius.circular(20)), child: CustomIconButton(height: 40.adaptSize, width: 40.adaptSize, padding: EdgeInsets.all(8.h), decoration: IconButtonStyleHelper.outline, onTap: () {onTapBtnBellTwo();}, child: CustomImageView(imagePath: ImageConstant.imgBell02)))]))); } 
/// Section Widget
Widget _buildPlay() { return Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(left: 16.h, top: 76.v, right: 16.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Row(crossAxisAlignment: CrossAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgPlay, height: 48.adaptSize, width: 48.adaptSize), Padding(padding: EdgeInsets.only(left: 10.h, top: 15.v, bottom: 10.v), child: Text("lbl_anjali_arora".tr, style: CustomTextStyles.titleMediumSemiBold)), Padding(padding: EdgeInsets.only(left: 2.h, top: 19.v, bottom: 13.v), child: Text("lbl2".tr, style: CustomTextStyles.bodySmallBluegray300)), Padding(padding: EdgeInsets.only(left: 2.h, top: 19.v, bottom: 13.v), child: Text("lbl_3d_ago".tr, style: CustomTextStyles.bodySmallBluegray300)), Spacer(), CustomImageView(imagePath: ImageConstant.imgMoreHorizontalBlueGray300, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 12.v, bottom: 10.v))]), SizedBox(height: 2.v), Container(height: 6.adaptSize, width: 6.adaptSize, margin: EdgeInsets.only(left: 6.h), decoration: BoxDecoration(color: theme.colorScheme.onPrimaryContainer.withOpacity(1), borderRadius: BorderRadius.circular(3.h)))]))); } 
/// Section Widget
Widget _buildBottomBar() { return CustomBottomBar(onChanged: (BottomBarEnum type) {Get.toNamed(getCurrentRoute(type), id: 1);}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.homePage; case BottomBarEnum.Search: return "/"; case BottomBarEnum.Message: return "/"; case BottomBarEnum.Feeds: return "/"; case BottomBarEnum.Profile: return "/"; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.homePage: return HomePage(); default: return DefaultWidget();} } 

/// Navigates to the previous screen.
onTapImgArrowLeft() { Get.back(); } 
/// Navigates to the notificationScreen when the action is triggered.
onTapBtnBellTwo() { Get.toNamed(AppRoutes.notificationScreen, ); } 
 }
