import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_leading_image.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_three.dart';import 'package:social_app/widgets/custom_icon_button.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/audio_call_one_controller.dart';class AudioCallOneScreen extends GetWidget<AudioCallOneController> {const AudioCallOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, backgroundColor: appTheme.gray900, appBar: _buildAppBar(), body: Container(width: SizeUtils.width, height: SizeUtils.height, padding: EdgeInsets.only(top: 24.v, bottom: 52.v), decoration: BoxDecoration(color: appTheme.gray900, image: DecorationImage(image: AssetImage(ImageConstant.imgGroup1038), fit: BoxFit.cover)), child: Container(width: double.maxFinite, padding: EdgeInsets.only(left: 126.h, top: 120.v, right: 126.h), child: Column(crossAxisAlignment: CrossAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgMaskGroup60x60, height: 120.adaptSize, width: 120.adaptSize, margin: EdgeInsets.only(right: 1.h)), SizedBox(height: 19.v), Text("lbl_anjali_arora".tr, style: CustomTextStyles.headlineSmallOnPrimaryContainer), SizedBox(height: 9.v), Padding(padding: EdgeInsets.only(right: 22.h), child: Text("lbl_ringing".tr, style: CustomTextStyles.bodyLargeOnPrimaryContainer)), SizedBox(height: 5.v)]))), bottomNavigationBar: _buildMicOffFILLW())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimarycontainer, margin: EdgeInsets.only(left: 16.h), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleThree(text: "msg_end_to_end_encrypted".tr)); } 
/// Section Widget
Widget _buildMicOffFILLW() { return Padding(padding: EdgeInsets.only(left: 27.h, right: 27.h, bottom: 54.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(right: 19.h), child: CustomIconButton(height: 52.adaptSize, width: 52.adaptSize, padding: EdgeInsets.all(14.h), decoration: IconButtonStyleHelper.fillOnPrimaryContainer, child: CustomImageView(imagePath: ImageConstant.imgVolumeUpFill0)))), Expanded(child: Padding(padding: EdgeInsets.symmetric(horizontal: 19.h), child: CustomIconButton(height: 52.adaptSize, width: 52.adaptSize, padding: EdgeInsets.all(16.h), decoration: IconButtonStyleHelper.fillOnPrimaryContainer, child: CustomImageView(imagePath: ImageConstant.imgVideoOnprimarycontainer)))), Expanded(child: Padding(padding: EdgeInsets.symmetric(horizontal: 19.h), child: CustomIconButton(height: 52.adaptSize, width: 52.adaptSize, padding: EdgeInsets.all(14.h), decoration: IconButtonStyleHelper.fillOnPrimaryContainer, child: CustomImageView(imagePath: ImageConstant.imgMicOffFill0W)))), Expanded(child: Padding(padding: EdgeInsets.only(left: 19.h), child: CustomIconButton(height: 52.adaptSize, width: 52.adaptSize, padding: EdgeInsets.all(12.h), decoration: IconButtonStyleHelper.fillPrimaryContainer, onTap: () {onTapBtnEndCall();}, child: CustomImageView(imagePath: ImageConstant.imgEndCall))))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the giveRatingScreen when the action is triggered.
onTapBtnEndCall() { Get.toNamed(AppRoutes.giveRatingScreen, ); } 
 }
