import 'package:social_app/widgets/custom_outlined_button.dart';import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_leading_image.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_six.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_two.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/following_one_controller.dart';class FollowingOneScreen extends GetWidget<FollowingOneController> {const FollowingOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.onPrimaryContainer.withOpacity(1), body: SizedBox(height: 768.v, width: double.maxFinite, child: Stack(alignment: Alignment.topRight, children: [Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 15.h, top: 163.v, right: 127.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_add_location".tr, style: CustomTextStyles.titleMediumBlack90001), SizedBox(height: 19.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomOutlinedButton(height: 32.v, width: 126.h, text: "msg_chandigarh_india".tr, buttonTextStyle: CustomTextStyles.titleSmallGray900), CustomOutlinedButton(height: 32.v, width: 96.h, text: "lbl_mohali_india".tr, buttonTextStyle: CustomTextStyles.titleSmallGray900)])]))), Align(alignment: Alignment.topRight, child: Container(width: 117.h, margin: EdgeInsets.only(top: 203.v), padding: EdgeInsets.symmetric(vertical: 6.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder5), child: Text("msg_mohali_chandigarh".tr, style: CustomTextStyles.titleSmallGray900))), Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(top: 245.v), child: SizedBox(width: double.maxFinite, child: Divider()))), Align(alignment: Alignment.center, child: Container(decoration: AppDecoration.fillOnPrimary, child: Column(mainAxisSize: MainAxisSize.min, children: [_buildArrowLeft(), Divider()])))])))); } 
/// Section Widget
Widget _buildArrowLeft() { return Container(padding: EdgeInsets.symmetric(vertical: 16.v), decoration: AppDecoration.fillOnPrimaryContainer, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, margin: EdgeInsets.only(left: 16.h), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleSix(text: "lbl_new_post2".tr), actions: [AppbarSubtitleTwo(text: "lbl_share".tr, margin: EdgeInsets.fromLTRB(16.h, 2.v, 16.h, 1.v), onTap: () {onTapShare();})]), SizedBox(height: 32.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Row(children: [Container(height: 52.adaptSize, width: 52.adaptSize, decoration: AppDecoration.fillBlueGray, child: CustomImageView(imagePath: ImageConstant.imgRectangle25244375x375, height: 52.adaptSize, width: 52.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 10.h, top: 17.v, bottom: 14.v), child: Text("msg_write_a_caption".tr, style: CustomTextStyles.titleMediumBluegray300))])), SizedBox(height: 9.v)])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the myProfilePostsTabContainerScreen when the action is triggered.
onTapShare() { Get.toNamed(AppRoutes.myProfilePostsTabContainerScreen, ); } 
 }
