import 'package:social_app/widgets/custom_search_view.dart';import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_title.dart';import 'package:social_app/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'widgets/frame_item_widget.dart';import 'models/frame_item_model.dart';import 'widgets/frame1_item_widget.dart';import 'models/frame1_item_model.dart';import 'widgets/frame2_item_widget.dart';import 'models/frame2_item_model.dart';import 'widgets/frame3_item_widget.dart';import 'models/frame3_item_model.dart';import 'widgets/frame4_item_widget.dart';import 'models/frame4_item_model.dart';import 'widgets/frame5_item_widget.dart';import 'models/frame5_item_model.dart';import 'widgets/frame6_item_widget.dart';import 'models/frame6_item_model.dart';import 'widgets/frame7_item_widget.dart';import 'models/frame7_item_model.dart';import 'widgets/frame8_item_widget.dart';import 'models/frame8_item_model.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/home_controller.dart';import 'models/home_model.dart';
// ignore_for_file: must_be_immutable
class HomePage extends StatelessWidget {HomePage({Key? key}) : super(key: key);

HomeController controller = Get.put(HomeController(HomeModel().obs));

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Container(width: double.maxFinite, decoration: AppDecoration.fillGray, child: Column(children: [_buildAccent(), SizedBox(height: 31.v), Expanded(child: SingleChildScrollView(child: Column(children: [Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: _buildFrame(trending: "lbl_trending".tr, seeAll: "lbl_see_all".tr, onTapFrame: () {onTapFrame();})), SizedBox(height: 17.v), _buildFrame3(), SizedBox(height: 29.v), Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: _buildFrame(trending: "lbl_featured".tr, seeAll: "lbl_see_all".tr)), SizedBox(height: 19.v), _buildFrame5(), SizedBox(height: 30.v), Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: _buildFrame(trending: "lbl_models".tr, seeAll: "lbl_see_all".tr)), SizedBox(height: 20.v), _buildFrame7(), SizedBox(height: 30.v), Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: _buildFrame(trending: "lbl_athletes".tr, seeAll: "lbl_see_all".tr)), SizedBox(height: 20.v), _buildFrame9(), SizedBox(height: 30.v), Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: _buildFrame(trending: "lbl_influencers".tr, seeAll: "lbl_see_all".tr)), SizedBox(height: 20.v), _buildFrame11(), SizedBox(height: 30.v), Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: _buildFrame(trending: "lbl_movie_artist".tr, seeAll: "lbl_see_all".tr)), SizedBox(height: 20.v), _buildFrame13(), SizedBox(height: 30.v), Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: _buildFrame(trending: "lbl_doctors".tr, seeAll: "lbl_see_all".tr)), SizedBox(height: 20.v), _buildFrame15(), SizedBox(height: 30.v), Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: _buildFrame(trending: "lbl_astrologer".tr, seeAll: "lbl_see_all".tr)), SizedBox(height: 20.v), _buildFrame17()])))])))); } 
/// Section Widget
Widget _buildAccent() { return SizedBox(height: 264.v, width: 359.h, child: Stack(alignment: Alignment.topLeft, children: [CustomImageView(imagePath: ImageConstant.imgAccent19, height: 252.v, width: 154.h, alignment: Alignment.topRight), Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(top: 66.v), child: CustomSearchView(width: 343.h, controller: controller.searchController, hintText: "msg_search_your_interest".tr, alignment: Alignment.topLeft))), CustomAppBar(height: 48.v, title: AppbarTitle(text: "lbl_discover".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgBell02, margin: EdgeInsets.symmetric(horizontal: 16.h), onTap: () {onTapBellTwo();})]), Align(alignment: Alignment.bottomCenter, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(right: 16.h), child: _buildFrame(trending: "lbl_category".tr, seeAll: "lbl_see_all".tr, onTapSeeAll: () {onTapTxtSeeAll();})), SizedBox(height: 17.v), SizedBox(height: 80.v, child: Obx(() => ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 15.h);}, itemCount: controller.homeModelObj.value.frameItemList.value.length, itemBuilder: (context, index) {FrameItemModel model = controller.homeModelObj.value.frameItemList.value[index]; return FrameItemWidget(model);})))]))])); } 
/// Section Widget
Widget _buildFrame3() { return SizedBox(height: 220.v, child: Obx(() => ListView.separated(padding: EdgeInsets.only(left: 16.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 10.h);}, itemCount: controller.homeModelObj.value.frame1ItemList.value.length, itemBuilder: (context, index) {Frame1ItemModel model = controller.homeModelObj.value.frame1ItemList.value[index]; return Frame1ItemWidget(model);}))); } 
/// Section Widget
Widget _buildFrame5() { return SizedBox(height: 220.v, child: Obx(() => ListView.separated(padding: EdgeInsets.only(left: 16.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 10.h);}, itemCount: controller.homeModelObj.value.frame2ItemList.value.length, itemBuilder: (context, index) {Frame2ItemModel model = controller.homeModelObj.value.frame2ItemList.value[index]; return Frame2ItemWidget(model);}))); } 
/// Section Widget
Widget _buildFrame7() { return SizedBox(height: 220.v, child: Obx(() => ListView.separated(padding: EdgeInsets.only(left: 16.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 10.h);}, itemCount: controller.homeModelObj.value.frame3ItemList.value.length, itemBuilder: (context, index) {Frame3ItemModel model = controller.homeModelObj.value.frame3ItemList.value[index]; return Frame3ItemWidget(model);}))); } 
/// Section Widget
Widget _buildFrame9() { return SizedBox(height: 220.v, child: Obx(() => ListView.separated(padding: EdgeInsets.only(left: 16.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 10.h);}, itemCount: controller.homeModelObj.value.frame4ItemList.value.length, itemBuilder: (context, index) {Frame4ItemModel model = controller.homeModelObj.value.frame4ItemList.value[index]; return Frame4ItemWidget(model);}))); } 
/// Section Widget
Widget _buildFrame11() { return SizedBox(height: 220.v, child: Obx(() => ListView.separated(padding: EdgeInsets.only(left: 16.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 10.h);}, itemCount: controller.homeModelObj.value.frame5ItemList.value.length, itemBuilder: (context, index) {Frame5ItemModel model = controller.homeModelObj.value.frame5ItemList.value[index]; return Frame5ItemWidget(model);}))); } 
/// Section Widget
Widget _buildFrame13() { return SizedBox(height: 220.v, child: Obx(() => ListView.separated(padding: EdgeInsets.only(left: 16.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 10.h);}, itemCount: controller.homeModelObj.value.frame6ItemList.value.length, itemBuilder: (context, index) {Frame6ItemModel model = controller.homeModelObj.value.frame6ItemList.value[index]; return Frame6ItemWidget(model);}))); } 
/// Section Widget
Widget _buildFrame15() { return SizedBox(height: 220.v, child: Obx(() => ListView.separated(padding: EdgeInsets.only(left: 16.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 10.h);}, itemCount: controller.homeModelObj.value.frame7ItemList.value.length, itemBuilder: (context, index) {Frame7ItemModel model = controller.homeModelObj.value.frame7ItemList.value[index]; return Frame7ItemWidget(model);}))); } 
/// Section Widget
Widget _buildFrame17() { return SizedBox(height: 220.v, child: Obx(() => ListView.separated(padding: EdgeInsets.only(left: 16.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 10.h);}, itemCount: controller.homeModelObj.value.frame8ItemList.value.length, itemBuilder: (context, index) {Frame8ItemModel model = controller.homeModelObj.value.frame8ItemList.value[index]; return Frame8ItemWidget(model);}))); } 
/// Common widget
Widget _buildFrame({required String trending, required String seeAll, Function? onTapFrame, Function? onTapSeeAll, }) { return GestureDetector(onTap: () {onTapFrame!.call();}, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Text(trending, style: theme.textTheme.titleLarge!.copyWith(color: appTheme.gray900)), GestureDetector(onTap: () {onTapSeeAll!.call();}, child: Padding(padding: EdgeInsets.only(bottom: 5.v), child: Text(seeAll, style: CustomTextStyles.titleMediumDeeporangeA200.copyWith(color: appTheme.deepOrangeA200))))])); } 
/// Navigates to the notificationScreen when the action is triggered.
onTapBellTwo() { Get.toNamed(AppRoutes.notificationScreen, ); } 
/// Navigates to the categoryScreen when the action is triggered.
onTapTxtSeeAll() { Get.toNamed(AppRoutes.categoryScreen, ); } 
/// Navigates to the trendingUserScreen when the action is triggered.
onTapFrame() { Get.toNamed(AppRoutes.trendingUserScreen, ); } 
 }
