import 'package:social_app/widgets/custom_outlined_button.dart';import 'package:social_app/core/utils/validation_functions.dart';import 'package:social_app/widgets/custom_text_form_field.dart';import 'package:social_app/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/settings_wallet_top_up_aadhaar_verification_controller.dart';
// ignore_for_file: must_be_immutable
class SettingsWalletTopUpAadhaarVerificationDialog extends StatelessWidget {SettingsWalletTopUpAadhaarVerificationDialog(this.controller, {Key? key}) : super(key: key);

SettingsWalletTopUpAadhaarVerificationController controller;

@override Widget build(BuildContext context) { return Container(width: 343.h, padding: EdgeInsets.all(10.h), decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgPlus, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.centerRight, onTap: () {onTapImgArrowRight();}), SizedBox(height: 16.v), Container(height: 74.adaptSize, width: 74.adaptSize, padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 21.v), decoration: AppDecoration.fillGreen.copyWith(borderRadius: BorderRadiusStyle.circleBorder37), child: CustomImageView(imagePath: ImageConstant.imgThumbsUpGreen400, height: 31.v, width: 34.h, alignment: Alignment.center)), SizedBox(height: 19.v), Text("msg_aadhaar_verification".tr, style: theme.textTheme.titleLarge), SizedBox(height: 9.v), Container(width: 292.h, margin: EdgeInsets.symmetric(horizontal: 15.h), child: Text("msg_as_per_regulations".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.titleMediumBluegray300)), SizedBox(height: 6.v), CustomOutlinedButton(height: 32.v, width: 150.h, text: "msg_takes_less_than".tr, leftIcon: Container(margin: EdgeInsets.only(right: 2.h), child: CustomImageView(imagePath: ImageConstant.imgFlash2, height: 16.adaptSize, width: 16.adaptSize)), buttonStyle: CustomButtonStyles.outlineLightGreen, buttonTextStyle: CustomTextStyles.bodySmallLightgreen40001), SizedBox(height: 29.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 6.h), child: Text("msg_enter_aadhaar_number".tr, style: theme.textTheme.titleSmall))), SizedBox(height: 6.v), Padding(padding: EdgeInsets.symmetric(horizontal: 6.h), child: CustomTextFormField(controller: controller.group75914Controller, hintText: "msg_enter_your_12_digit".tr, hintStyle: CustomTextStyles.titleMediumBluegray300, textInputAction: TextInputAction.done, textInputType: TextInputType.number, validator: (value) {if (!isNumeric(value)) {return "err_msg_please_enter_valid_number".tr;} return null;})), SizedBox(height: 15.v), CustomElevatedButton(text: "lbl_verify".tr, margin: EdgeInsets.symmetric(horizontal: 6.h), onPressed: () {onTapVerify();}), SizedBox(height: 20.v)])); } 
/// Navigates to the settingsWalletOneScreen when the action is triggered.
onTapImgArrowRight() { Get.toNamed(AppRoutes.settingsWalletOneScreen, ); } 
/// Navigates to the settingsWalletTopUpScreen when the action is triggered.
onTapVerify() { Get.toNamed(AppRoutes.settingsWalletTopUpScreen, ); } 
 }
