import 'package:social_app/widgets/custom_search_view.dart';import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_title_image.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_six.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_five.dart';import 'package:social_app/widgets/custom_radio_button.dart';import 'package:social_app/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/registration_step_8_active_controller.dart';class RegistrationStep8ActiveScreen extends GetWidget<RegistrationStep8ActiveController> {const RegistrationStep8ActiveScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [_buildAccent(), SizedBox(height: 8.v), Expanded(child: SingleChildScrollView(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_healthcare".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 5.v), SizedBox(height: 496.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [_buildGroup1073(), _buildThirtyEight(), _buildDietitian()]))])))])))); } 
/// Section Widget
Widget _buildAccent() { return SizedBox(height: 252.v, width: double.maxFinite, child: Stack(alignment: Alignment.topLeft, children: [CustomImageView(imagePath: ImageConstant.imgAccent16, height: 252.v, width: 154.h, alignment: Alignment.centerRight), Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 16.h, top: 91.v), child: Text("msg_what_s_your_profession".tr, style: theme.textTheme.headlineSmall))), Align(alignment: Alignment.bottomLeft, child: Container(width: 313.h, margin: EdgeInsets.only(left: 16.h, bottom: 90.v), child: Text("msg_pick_your_favorite".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.titleSmall))), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 23.v), child: CustomSearchView(width: 343.h, controller: controller.searchController, hintText: "msg_search_your_profession".tr, alignment: Alignment.bottomCenter))), CustomAppBar(height: 59.v, centerTitle: true, title: Column(children: [Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Row(children: [AppbarTitleImage(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, onTap: () {onTapArrowLeft();}), AppbarSubtitleSix(text: "lbl_step_8_of_8".tr, margin: EdgeInsets.only(left: 109.h, top: 3.v)), AppbarSubtitleFive(text: "lbl_skip".tr, margin: EdgeInsets.only(left: 105.h, top: 3.v))])), SizedBox(height: 16.v), SizedBox(height: 3.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: SizedBox(width: double.maxFinite, child: Divider(color: appTheme.gray10001))), Align(alignment: Alignment.center, child: SizedBox(width: double.maxFinite, child: Divider(color: appTheme.green400)))]))]), styleType: Style.bgFill_2)])); } 
/// Section Widget
Widget _buildGroup1073() { return Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(top: 372.v), child: Obx(() => Column(children: [CustomRadioButton(text: "lbl_dermatologists".tr, value: controller.registrationStep8ActiveModelObj.value.radioList.value[0], groupValue: controller.radioGroup.value, padding: EdgeInsets.fromLTRB(10.h, 19.v, 30.h, 19.v), onChange: (value) {controller.radioGroup.value = value;}), CustomRadioButton(text: "lbl_radiologists".tr, value: controller.registrationStep8ActiveModelObj.value.radioList.value[1], groupValue: controller.radioGroup.value, padding: EdgeInsets.fromLTRB(10.h, 19.v, 30.h, 19.v), onChange: (value) {controller.radioGroup.value = value;})])))); } 
/// Section Widget
Widget _buildThirtyEight() { return Align(alignment: Alignment.bottomCenter, child: Container(margin: EdgeInsets.only(bottom: 14.v), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 54.v), decoration: AppDecoration.gradientGrayToGray, child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 33.v), CustomElevatedButton(text: "lbl_continue".tr, onPressed: () {onTapContinue();})]))); } 
/// Section Widget
Widget _buildDietitian() { return Align(alignment: Alignment.topCenter, child: Column(mainAxisSize: MainAxisSize.min, children: [Obx(() => Column(children: [CustomRadioButton(text: "lbl_dietitian".tr, value: controller.registrationStep8ActiveModelObj.value.radioList1.value[0], groupValue: controller.radioGroup1.value, padding: EdgeInsets.fromLTRB(10.h, 20.v, 30.h, 20.v), onChange: (value) {controller.radioGroup1.value = value;}), CustomRadioButton(text: "lbl_nurse".tr, value: controller.registrationStep8ActiveModelObj.value.radioList1.value[1], groupValue: controller.radioGroup1.value, padding: EdgeInsets.fromLTRB(10.h, 20.v, 30.h, 20.v), onChange: (value) {controller.radioGroup1.value = value;})])), Container(width: double.maxFinite, padding: EdgeInsets.fromLTRB(16.h, 19.v, 16.h, 18.v), decoration: AppDecoration.outlineGray30001, child: Row(children: [Container(height: 24.adaptSize, width: 24.adaptSize, padding: EdgeInsets.all(6.h), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: CustomImageView(imagePath: ImageConstant.imgCheckGray900, height: 12.adaptSize, width: 12.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 10.h, top: 3.v), child: Text("lbl_orthoptist".tr, style: theme.textTheme.titleMedium))])), Obx(() => Column(children: [CustomRadioButton(text: "lbl_pharmacist".tr, value: controller.registrationStep8ActiveModelObj.value.radioList2.value[0], groupValue: controller.radioGroup2.value, padding: EdgeInsets.fromLTRB(10.h, 20.v, 30.h, 20.v), onChange: (value) {controller.radioGroup2.value = value;}), CustomRadioButton(text: "lbl_cardiologists".tr, value: controller.registrationStep8ActiveModelObj.value.radioList2.value[1], groupValue: controller.radioGroup2.value, padding: EdgeInsets.fromLTRB(10.h, 19.v, 30.h, 19.v), onChange: (value) {controller.radioGroup2.value = value;}), CustomRadioButton(text: "msg_anesthesiologists".tr, value: controller.registrationStep8ActiveModelObj.value.radioList2.value[2], groupValue: controller.radioGroup2.value, padding: EdgeInsets.fromLTRB(10.h, 19.v, 30.h, 19.v), onChange: (value) {controller.radioGroup2.value = value;})]))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the registrationCompleteScreen when the action is triggered.
onTapContinue() { Get.toNamed(AppRoutes.registrationCompleteScreen, ); } 
 }
