import 'package:social_app/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/location_permission_controller.dart';class LocationPermissionScreen extends GetWidget<LocationPermissionController> {const LocationPermissionScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(height: 768.v, width: double.maxFinite, child: Stack(alignment: Alignment.topLeft, children: [CustomImageView(imagePath: ImageConstant.imgAccent18, height: 252.v, width: 154.h, alignment: Alignment.topRight), CustomImageView(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.topLeft, margin: EdgeInsets.only(left: 16.h, top: 16.v), onTap: () {onTapImgArrowLeft();}), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 54.v), child: Column(mainAxisSize: MainAxisSize.min, children: [Container(margin: EdgeInsets.symmetric(horizontal: 101.h), padding: EdgeInsets.all(24.h), decoration: AppDecoration.fillGreen.copyWith(borderRadius: BorderRadiusStyle.circleBorder70), child: Container(height: 92.adaptSize, width: 92.adaptSize, padding: EdgeInsets.all(22.h), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.circleBorder46), child: CustomImageView(imagePath: ImageConstant.imgIconOnprimarycontainer, height: 48.adaptSize, width: 48.adaptSize, alignment: Alignment.center))), SizedBox(height: 22.v), Text("lbl_congratulations".tr, style: CustomTextStyles.headlineSmallBold), SizedBox(height: 8.v), Text("msg_your_account_has".tr, style: theme.textTheme.titleSmall), SizedBox(height: 187.v), _buildContinue()]))), Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(horizontal: 52.h, vertical: 147.v), decoration: AppDecoration.fillOnPrimary, child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [Container(margin: EdgeInsets.only(left: 1.h), padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 14.v), decoration: AppDecoration.fillGrayEa.copyWith(borderRadius: BorderRadiusStyle.customBorderTL14), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [Container(width: 194.h, margin: EdgeInsets.only(left: 15.h, right: 19.h), child: Text("msg_allow_social_to".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.titleMediumSFProTextBlack90001.copyWith(height: 1.29))), SizedBox(height: 2.v), SizedBox(width: 228.h, child: Text("msg_we_use_your_location".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.labelLargeSFProTextBlack90001.copyWith(height: 1.38)))])), CustomImageView(imagePath: ImageConstant.imgImage32, height: 181.v, width: 270.h), SizedBox(height: 44.v), Padding(padding: EdgeInsets.only(left: 1.h), child: Column(children: [_buildAllowOnce(), _buildAllowWhileUsingApp(), _buildDontAllow()]))])))])))); } 
/// Section Widget
Widget _buildContinue() { return CustomElevatedButton(text: "lbl_continue".tr); } 
/// Section Widget
Widget _buildAllowOnce() { return CustomElevatedButton(height: 44.v, text: "lbl_allow_once".tr, buttonStyle: CustomButtonStyles.fillGrayEa, buttonTextStyle: CustomTextStyles.bodyLargeSFProTextBlueA400, onPressed: () {onTapAllowOnce();}); } 
/// Section Widget
Widget _buildAllowWhileUsingApp() { return CustomElevatedButton(height: 44.v, text: "msg_allow_while_using".tr, buttonStyle: CustomButtonStyles.fillGrayEa, buttonTextStyle: CustomTextStyles.bodyLargeSFProTextBlueA400); } 
/// Section Widget
Widget _buildDontAllow() { return CustomElevatedButton(height: 44.v, text: "lbl_don_t_allow".tr, buttonStyle: CustomButtonStyles.fillGrayEaBL14, buttonTextStyle: CustomTextStyles.bodyLargeSFProTextBlueA400); } 

/// Navigates to the previous screen.
onTapImgArrowLeft() { Get.back(); } 
/// Navigates to the homeContainerScreen when the action is triggered.
onTapAllowOnce() { Get.toNamed(AppRoutes.homeContainerScreen, ); } 
 }
