import 'package:social_app/presentation/home_page/home_page.dart';import 'package:social_app/widgets/custom_search_view.dart';import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_leading_image.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle.dart';import 'package:social_app/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'widgets/anjaliarora_item_widget.dart';import 'models/anjaliarora_item_model.dart';import 'widgets/anjaliarora1_item_widget.dart';import 'models/anjaliarora1_item_model.dart';import 'package:social_app/widgets/custom_bottom_bar.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/message_controller.dart';class MessageScreen extends GetWidget<MessageController> {const MessageScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildAccent(), SizedBox(height: 9.v), Expanded(child: Align(alignment: Alignment.center, child: SingleChildScrollView(child: Container(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_recent_messages".tr, style: CustomTextStyles.titleMediumBold), SizedBox(height: 17.v), _buildAnjaliArora(), SizedBox(height: 98.v), _buildFrame()])))))])), bottomNavigationBar: _buildBottomBar())); } 
/// Section Widget
Widget _buildAccent() { return Align(alignment: Alignment.centerRight, child: SizedBox(height: 252.v, width: 370.h, child: Stack(alignment: Alignment.topLeft, children: [CustomImageView(imagePath: ImageConstant.imgAccent30, height: 252.v, width: 154.h, alignment: Alignment.centerRight, margin: EdgeInsets.only(right: 11.h)), Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(top: 66.v), child: CustomSearchView(width: 343.h, controller: controller.searchController, hintText: "lbl_search".tr, alignment: Alignment.topLeft))), CustomAppBar(height: 48.v, leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, margin: EdgeInsets.only(left: 16.h, top: 8.v, bottom: 8.v), onTap: () {onTapArrowLeft();}), title: AppbarSubtitle(text: "lbl_inbox".tr, margin: EdgeInsets.only(left: 15.h)), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgBell02, margin: EdgeInsets.symmetric(horizontal: 16.h), onTap: () {onTapBellTwo();})]), Align(alignment: Alignment.bottomCenter, child: SizedBox(height: 251.v, child: Obx(() => ListView.separated(padding: EdgeInsets.only(top: 138.v, bottom: 19.v), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 20.h);}, itemCount: controller.messageModelObj.value.anjaliaroraItemList.value.length, itemBuilder: (context, index) {AnjaliaroraItemModel model = controller.messageModelObj.value.anjaliaroraItemList.value[index]; return AnjaliaroraItemWidget(model);}))))]))); } 
/// Section Widget
Widget _buildAnjaliArora() { return Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 20.v);}, itemCount: controller.messageModelObj.value.anjaliarora1ItemList.value.length, itemBuilder: (context, index) {Anjaliarora1ItemModel model = controller.messageModelObj.value.anjaliarora1ItemList.value[index]; return Anjaliarora1ItemWidget(model, onTapFrame: () {onTapFrame();});})); } 
/// Section Widget
Widget _buildFrame() { return Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgEllipse134, height: 58.adaptSize, width: 58.adaptSize, radius: BorderRadius.circular(29.h)), Expanded(child: Padding(padding: EdgeInsets.only(left: 15.h, top: 4.v, bottom: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(width: 270.h, child: Row(children: [Text("lbl_aachal_sharma".tr, style: CustomTextStyles.titleMediumSemiBold), CustomImageView(imagePath: ImageConstant.imgVerified, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 2.h, top: 2.v, bottom: 2.v)), Spacer(), Text("lbl_yesterday".tr, textAlign: TextAlign.right, style: CustomTextStyles.bodyMediumLight)])), SizedBox(height: 6.v), Text("msg_you_can_you_sent2".tr, style: theme.textTheme.bodyLarge)])))]); } 
/// Section Widget
Widget _buildBottomBar() { return CustomBottomBar(onChanged: (BottomBarEnum type) {Get.toNamed(getCurrentRoute(type), id: 1);}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.homePage; case BottomBarEnum.Search: return "/"; case BottomBarEnum.Message: return "/"; case BottomBarEnum.Feeds: return "/"; case BottomBarEnum.Profile: return "/"; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.homePage: return HomePage(); default: return DefaultWidget();} } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the notificationScreen when the action is triggered.
onTapBellTwo() { Get.toNamed(AppRoutes.notificationScreen, ); } 
/// Navigates to the messageChatWithUserDefaultScreen when the action is triggered.
onTapFrame() { Get.toNamed(AppRoutes.messageChatWithUserDefaultScreen, ); } 
 }
