import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_leading_image.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_six.dart';import 'package:social_app/widgets/custom_search_view.dart';import 'package:social_app/widgets/custom_elevated_button.dart';import 'package:social_app/widgets/custom_radio_button.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/setting_edit_profile_profession_controller.dart';class SettingEditProfileProfessionScreen extends GetWidget<SettingEditProfileProfessionController> {const SettingEditProfileProfessionScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: SizedBox(height: 768.v, width: double.maxFinite, child: Stack(alignment: Alignment.topLeft, children: [CustomImageView(imagePath: ImageConstant.imgAccent40, height: 252.v, width: 154.h, alignment: Alignment.topRight), Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 16.h, top: 154.v), child: Text("lbl_healthcare".tr, style: theme.textTheme.titleMedium))), Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(top: 71.v), child: CustomSearchView(width: 343.h, controller: controller.searchController, hintText: "msg_search_your_profession".tr, alignment: Alignment.topCenter))), _buildSave(), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 92.v), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildGroup1310(), _buildCheck(), _buildGroup1311()])))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, margin: EdgeInsets.only(left: 16.h), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleSix(text: "lbl_edit_profession".tr)); } 
/// Section Widget
Widget _buildSave() { return Align(alignment: Alignment.bottomCenter, child: Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 54.v), decoration: AppDecoration.gradientGrayToGray, child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 33.v), CustomElevatedButton(text: "lbl_save".tr, onPressed: () {onTapSave();})]))); } 
/// Section Widget
Widget _buildGroup1310() { return Obx(() => Column(children: [CustomRadioButton(text: "lbl_dietitian".tr, value: controller.settingEditProfileProfessionModelObj.value.radioList.value[0], groupValue: controller.radioGroup.value, padding: EdgeInsets.fromLTRB(10.h, 20.v, 30.h, 20.v), onChange: (value) {controller.radioGroup.value = value;}), CustomRadioButton(text: "lbl_nurse".tr, value: controller.settingEditProfileProfessionModelObj.value.radioList.value[1], groupValue: controller.radioGroup.value, padding: EdgeInsets.fromLTRB(10.h, 20.v, 30.h, 20.v), onChange: (value) {controller.radioGroup.value = value;})])); } 
/// Section Widget
Widget _buildCheck() { return Container(width: double.maxFinite, padding: EdgeInsets.fromLTRB(16.h, 19.v, 16.h, 18.v), decoration: AppDecoration.outlineGray30001, child: Row(children: [Container(height: 24.adaptSize, width: 24.adaptSize, padding: EdgeInsets.all(6.h), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: CustomImageView(imagePath: ImageConstant.imgCheckGray900, height: 12.adaptSize, width: 12.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 10.h, top: 3.v), child: Text("lbl_orthoptist".tr, style: theme.textTheme.titleMedium))])); } 
/// Section Widget
Widget _buildGroup1311() { return Obx(() => Column(children: [CustomRadioButton(text: "lbl_pharmacist".tr, value: controller.settingEditProfileProfessionModelObj.value.radioList1.value[0], groupValue: controller.radioGroup1.value, padding: EdgeInsets.fromLTRB(10.h, 20.v, 30.h, 20.v), onChange: (value) {controller.radioGroup1.value = value;}), CustomRadioButton(text: "lbl_cardiologists".tr, value: controller.settingEditProfileProfessionModelObj.value.radioList1.value[1], groupValue: controller.radioGroup1.value, padding: EdgeInsets.fromLTRB(10.h, 19.v, 30.h, 19.v), onChange: (value) {controller.radioGroup1.value = value;}), CustomRadioButton(text: "msg_anesthesiologists".tr, value: controller.settingEditProfileProfessionModelObj.value.radioList1.value[2], groupValue: controller.radioGroup1.value, padding: EdgeInsets.fromLTRB(10.h, 19.v, 30.h, 19.v), onChange: (value) {controller.radioGroup1.value = value;}), CustomRadioButton(text: "lbl_dermatologists".tr, value: controller.settingEditProfileProfessionModelObj.value.radioList1.value[3], groupValue: controller.radioGroup1.value, padding: EdgeInsets.fromLTRB(10.h, 19.v, 30.h, 19.v), onChange: (value) {controller.radioGroup1.value = value;}), CustomRadioButton(text: "lbl_radiologists".tr, value: controller.settingEditProfileProfessionModelObj.value.radioList1.value[4], groupValue: controller.radioGroup1.value, padding: EdgeInsets.fromLTRB(10.h, 19.v, 30.h, 19.v), onChange: (value) {controller.radioGroup1.value = value;})])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the settingEditProfileScreen when the action is triggered.
onTapSave() { Get.toNamed(AppRoutes.settingEditProfileScreen, ); } 
 }
