import 'package:social_app/widgets/custom_icon_button.dart';import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_title_image.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_six.dart';import 'package:social_app/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/registration_s3_controller.dart';class RegistrationS3Screen extends GetWidget<RegistrationS3Controller> {const RegistrationS3Screen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildAccent(), SizedBox(height: 336.v, width: double.maxFinite), Spacer()])), bottomNavigationBar: _buildContinue())); } 
/// Section Widget
Widget _buildAccent() { return SizedBox(height: 336.v, width: double.maxFinite, child: Stack(alignment: Alignment.topLeft, children: [CustomImageView(imagePath: ImageConstant.imgAccent8, height: 252.v, width: 154.h, alignment: Alignment.topRight), Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 16.h, top: 91.v), child: Text("msg_what_s_your_gender".tr, style: theme.textTheme.headlineSmall))), Align(alignment: Alignment.topLeft, child: Container(width: 323.h, margin: EdgeInsets.only(left: 16.h, top: 127.v), child: Text("msg_this_help_us_find".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.titleSmall))), Align(alignment: Alignment.bottomLeft, child: Container(margin: EdgeInsets.only(left: 16.h, right: 195.h), padding: EdgeInsets.symmetric(horizontal: 51.h, vertical: 27.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomIconButton(height: 60.adaptSize, width: 60.adaptSize, padding: EdgeInsets.all(12.h), decoration: IconButtonStyleHelper.fillPrimary, child: CustomImageView(imagePath: ImageConstant.imgIconGray900)), SizedBox(height: 5.v), Text("lbl_male".tr, style: theme.textTheme.titleMedium)]))), Align(alignment: Alignment.bottomRight, child: Container(margin: EdgeInsets.only(left: 196.h, right: 16.h), padding: EdgeInsets.symmetric(horizontal: 50.h, vertical: 25.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomIconButton(height: 60.adaptSize, width: 60.adaptSize, padding: EdgeInsets.all(12.h), decoration: IconButtonStyleHelper.fillGray, child: CustomImageView(imagePath: ImageConstant.imgIconBlueGray300)), SizedBox(height: 9.v), Text("lbl_female".tr, style: CustomTextStyles.titleMediumBluegray300)]))), CustomAppBar(height: 59.v, centerTitle: true, title: Column(children: [Padding(padding: EdgeInsets.only(left: 16.h, right: 150.h), child: Row(children: [AppbarTitleImage(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, onTap: () {onTapArrowLeft();}), AppbarSubtitleSix(text: "lbl_step_3_of_8".tr, margin: EdgeInsets.only(left: 109.h, top: 3.v))])), SizedBox(height: 16.v), SizedBox(height: 3.v, width: double.maxFinite, child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.center, child: SizedBox(width: double.maxFinite, child: Divider(color: appTheme.gray10001))), Align(alignment: Alignment.centerLeft, child: SizedBox(width: double.maxFinite, child: Divider(color: appTheme.green400, endIndent: 235.h)))]))]), styleType: Style.bgFill)])); } 
/// Section Widget
Widget _buildContinue() { return CustomElevatedButton(text: "lbl_continue".tr, margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 54.v)); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
