import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_title_image.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_six.dart';import 'package:social_app/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/registration_step2_controller.dart';class RegistrationStep2Screen extends GetWidget<RegistrationStep2Controller> {const RegistrationStep2Screen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildAccent(), SizedBox(height: 252.v, width: double.maxFinite), Spacer()])), bottomNavigationBar: _buildContinue())); } 
/// Section Widget
Widget _buildInputField() { return Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 2.v), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_date_of_birth_dd_mm_yyyy".tr, style: theme.textTheme.titleSmall), SizedBox(height: 5.v), Container(padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 13.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 2.v, bottom: 1.v), child: Text("lbl_25_11_1992".tr, style: theme.textTheme.titleMedium)), CustomImageView(imagePath: ImageConstant.imgCalendar, height: 24.adaptSize, width: 24.adaptSize)]))]))); } 
/// Section Widget
Widget _buildAccent() { return SizedBox(height: 252.v, width: double.maxFinite, child: Stack(alignment: Alignment.topLeft, children: [CustomImageView(imagePath: ImageConstant.imgAccent7, height: 252.v, width: 154.h, alignment: Alignment.centerRight), Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 16.h, top: 91.v), child: Text("msg_when_s_your_birthday".tr, style: theme.textTheme.headlineSmall))), Align(alignment: Alignment.bottomLeft, child: Padding(padding: EdgeInsets.only(left: 16.h, bottom: 106.v), child: Text("msg_your_birthday_won_t".tr, style: theme.textTheme.titleSmall))), _buildInputField(), CustomAppBar(height: 59.v, centerTitle: true, title: Column(children: [Padding(padding: EdgeInsets.only(left: 16.h, right: 150.h), child: Row(children: [AppbarTitleImage(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, onTap: () {onTapArrowLeft();}), AppbarSubtitleSix(text: "lbl_step_2_of_8".tr, margin: EdgeInsets.only(left: 110.h, top: 3.v))])), SizedBox(height: 16.v), SizedBox(height: 3.v, width: double.maxFinite, child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.center, child: SizedBox(width: double.maxFinite, child: Divider(color: appTheme.gray10001))), Align(alignment: Alignment.centerLeft, child: SizedBox(width: double.maxFinite, child: Divider(color: appTheme.green400, endIndent: 282.h)))]))]), styleType: Style.bgFill)])); } 
/// Section Widget
Widget _buildContinue() { return CustomElevatedButton(text: "lbl_continue".tr, margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 54.v)); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
