import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_leading_image.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_one.dart';import 'package:social_app/widgets/app_bar/appbar_title_image.dart';import 'package:social_app/widgets/app_bar/appbar_trailing_button_one.dart';import 'package:social_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:social_app/widgets/custom_text_form_field.dart';import 'package:social_app/widgets/custom_icon_button.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/message_start_message_controller.dart';class MessageStartMessageScreen extends GetWidget<MessageStartMessageController> {const MessageStartMessageScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [_buildThreeThousand(), Container(padding: EdgeInsets.symmetric(horizontal: 28.h, vertical: 18.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgCloseOnprimarycontainer, height: 69.v, width: 58.h), SizedBox(height: 21.v), Text("msg_say_hi_to_taranvir".tr, style: CustomTextStyles.titleMediumSemiBold), SizedBox(height: 7.v), SizedBox(width: 317.h, child: Text("msg_you_have_250_characters".tr, maxLines: 3, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.titleMediumBluegray300)), SizedBox(height: 5.v)]))])), bottomNavigationBar: _buildSeventyThree())); } 
/// Section Widget
Widget _buildThreeThousand() { return SizedBox(height: 252.v, width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgAccent29, height: 252.v, width: 154.h, alignment: Alignment.centerRight), CustomAppBar(height: 56.v, leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, margin: EdgeInsets.only(left: 16.h, top: 16.v, bottom: 16.v), onTap: () {onTapArrowLeft();}), title: Padding(padding: EdgeInsets.only(left: 10.h), child: Row(children: [AppbarSubtitleOne(text: "lbl_taranvir_k".tr), AppbarTitleImage(imagePath: ImageConstant.imgVerified, margin: EdgeInsets.only(left: 2.h, top: 3.v, bottom: 2.v))])), actions: [AppbarTrailingButtonOne(margin: EdgeInsets.only(left: 16.h, top: 8.v, right: 8.h)), AppbarTrailingImage(imagePath: ImageConstant.imgVideo, margin: EdgeInsets.fromLTRB(20.h, 18.v, 8.h, 10.v)), AppbarTrailingImage(imagePath: ImageConstant.imgPhoneGray900, margin: EdgeInsets.fromLTRB(20.h, 18.v, 24.h, 10.v))], styleType: Style.bgFill_3)])); } 
/// Section Widget
Widget _buildSeventyThree() { return Container(margin: EdgeInsets.only(bottom: 41.v), decoration: AppDecoration.outlineBlack90001, child: Column(mainAxisSize: MainAxisSize.min, children: [Divider(), Padding(padding: EdgeInsets.only(left: 16.h, top: 6.v, right: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomTextFormField(controller: controller.messageController, hintText: "msg_write_a_message".tr, hintStyle: CustomTextStyles.titleMediumBluegray300, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(15.h, 14.v, 10.h, 14.v), child: CustomImageView(imagePath: ImageConstant.imgSmile, height: 24.adaptSize, width: 24.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 52.v), contentPadding: EdgeInsets.only(top: 16.v, right: 30.h, bottom: 16.v), borderDecoration: TextFormFieldStyleHelper.outlineGrayTL26, fillColor: appTheme.gray20002)), Padding(padding: EdgeInsets.only(left: 6.h), child: CustomIconButton(height: 52.adaptSize, width: 52.adaptSize, padding: EdgeInsets.all(14.h), decoration: IconButtonStyleHelper.fillPrimaryTL24, child: CustomImageView(imagePath: ImageConstant.imgIconSolidPaperAirplane)))]))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
