import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_leading_image.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_six.dart';import 'package:social_app/widgets/custom_search_view.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/following_three_controller.dart';class FollowingThreeScreen extends GetWidget<FollowingThreeController> {const FollowingThreeScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, backgroundColor: theme.colorScheme.onPrimaryContainer.withOpacity(1), appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 26.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomSearchView(controller: controller.searchController, hintText: "msg_search_for_a_location".tr, borderDecoration: SearchViewStyleHelper.outlineGrayTL26, fillColor: appTheme.gray30001), SizedBox(height: 30.v), Text("msg_chandigarh_india".tr, style: CustomTextStyles.bodyLargeBlack90001), Text("lbl_11_9km".tr, style: CustomTextStyles.bodyMediumBlack90001), SizedBox(height: 20.v), Text("lbl_mohali_india".tr, style: CustomTextStyles.bodyLargeBlack90001), SizedBox(height: 2.v), Text("msg_5_6km_chandigarh".tr, style: CustomTextStyles.bodyMediumBlack90001), SizedBox(height: 19.v), Text("msg_tdi_city_sector".tr, style: CustomTextStyles.bodyLargeBlack90001), Text("lbl_0km".tr, style: CustomTextStyles.bodyMediumBlack90001), SizedBox(height: 21.v), Text("lbl_chandigarh".tr, style: CustomTextStyles.bodyLargeBlack90001), Text("lbl_13_2km".tr, style: CustomTextStyles.bodyMediumBlack90001), SizedBox(height: 21.v), Text("msg_cgc_landran_campus".tr, style: CustomTextStyles.bodyLargeBlack90001), Text("lbl_0_9km".tr, style: CustomTextStyles.bodyMediumBlack90001), SizedBox(height: 19.v), Text("lbl_nexus_elante".tr, style: CustomTextStyles.bodyLargeBlack90001), SizedBox(height: 3.v), Text("msg_13_1km_industrial".tr, style: CustomTextStyles.bodyMediumBlack90001), SizedBox(height: 19.v), Text("lbl_vr_punjab".tr, style: CustomTextStyles.bodyLargeBlack90001), SizedBox(height: 1.v), Text("msg_6_6km_vr_punjab".tr, style: CustomTextStyles.bodyMediumBlack90001), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, margin: EdgeInsets.only(left: 16.h), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleSix(text: "lbl_locations".tr)); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
