import 'package:social_app/widgets/custom_icon_button.dart';import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_leading_image.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_six.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/setting_about_us_controller.dart';class SettingAboutUsScreen extends GetWidget<SettingAboutUsController> {const SettingAboutUsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(height: 768.v, width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgAccent84, height: 252.v, width: 154.h, alignment: Alignment.topRight), _buildPrivacyPolicy1()])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, margin: EdgeInsets.only(left: 16.h), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleSix(text: "lbl_about_us".tr)); } 
/// Section Widget
Widget _buildPrivacyPolicy1() { return Align(alignment: Alignment.topCenter, child: Container(margin: EdgeInsets.only(left: 16.h, top: 71.v, right: 16.h), decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildCreditCard(cookiesPolicy: "lbl_privacy_policy2".tr, onTapCreditCard8: () {onTapPrivacyPolicy();}), Container(padding: EdgeInsets.fromLTRB(15.h, 16.v, 15.h, 15.v), decoration: AppDecoration.outlineGray300011, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: 44.adaptSize, width: 44.adaptSize, padding: EdgeInsets.all(10.h), decoration: AppDecoration.fillDeepPurple.copyWith(borderRadius: BorderRadiusStyle.circleBorder23), child: CustomImageView(imagePath: ImageConstant.imgCalendarDeepPurple300, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 15.h, top: 12.v, bottom: 11.v), child: Text("msg_terms_conditions".tr, style: theme.textTheme.titleMedium)), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 10.v))])), _buildCreditCard(cookiesPolicy: "lbl_cookies_policy".tr, onTapCreditCard8: () {onTapCreditCard();})]))); } 
/// Common widget
Widget _buildCreditCard({required String cookiesPolicy, Function? onTapCreditCard8, }) { return GestureDetector(onTap: () {onTapCreditCard8!.call();}, child: Container(padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 16.v), decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.customBorderBL20), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomIconButton(height: 44.adaptSize, width: 44.adaptSize, padding: EdgeInsets.all(10.h), child: CustomImageView(imagePath: ImageConstant.imgCreditCard)), Padding(padding: EdgeInsets.only(left: 15.h, top: 13.v, bottom: 10.v), child: Text(cookiesPolicy, style: theme.textTheme.titleMedium!.copyWith(color: appTheme.gray900))), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 10.v))]))); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the settingAboutUsPrivacyPolicyOneScreen when the action is triggered.
onTapPrivacyPolicy() { Get.toNamed(AppRoutes.settingAboutUsPrivacyPolicyOneScreen, ); } 
/// Navigates to the settingAboutUsPrivacyPolicyScreen when the action is triggered.
onTapCreditCard() { Get.toNamed(AppRoutes.settingAboutUsPrivacyPolicyScreen, ); } 
 }
