import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_leading_image.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_six.dart';import 'models/frame11_item_model.dart';import '../settings_wallet_top_up_screen/widgets/frame11_item_widget.dart';import 'package:social_app/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/settings_wallet_top_up_controller.dart';class SettingsWalletTopUpScreen extends GetWidget<SettingsWalletTopUpController> {const SettingsWalletTopUpScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildAccent(), Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 49.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 89.v), _buildInbox(), SizedBox(height: 12.v), Divider(), SizedBox(height: 13.v), _buildDepositAmountExcl(depositAmountExcl: "msg_add_to_current_balance".tr, price: "lbl_150_00".tr), SizedBox(height: 14.v), _buildDepositAmountExcl(depositAmountExcl: "msg_deposit_amount_excl".tr, price: "lbl_117_18".tr), SizedBox(height: 13.v), _buildDepositAmountExcl(depositAmountExcl: "msg_govt_tax_28_gst".tr, price: "lbl_32_82".tr), SizedBox(height: 14.v), _buildDepositAmountExcl(depositAmountExcl: "lbl_platfrom_fee".tr, price: "lbl_5_002".tr), SizedBox(height: 15.v), Divider(), SizedBox(height: 8.v), _buildDepositAmountExcl(depositAmountExcl: "lbl_total_amount".tr, price: "lbl_112_18".tr)]))])), bottomNavigationBar: _buildTop150())); } 
/// Section Widget
Widget _buildAccent() { return SizedBox(height: 252.v, width: 359.h, child: Stack(alignment: Alignment.topLeft, children: [CustomImageView(imagePath: ImageConstant.imgAccent55, height: 252.v, width: 154.h, alignment: Alignment.centerRight), Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(top: 16.v, right: 163.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, margin: EdgeInsets.only(left: 16.h), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleSix(text: "lbl_top_up".tr)), SizedBox(height: 25.v), Text("lbl_enter_amount".tr, style: CustomTextStyles.titleMediumBluegray300), SizedBox(height: 11.v), Padding(padding: EdgeInsets.only(right: 24.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [RichText(text: TextSpan(children: [TextSpan(text: "lbl3".tr, style: CustomTextStyles.displaySmallff95a4b7), TextSpan(text: "lbl_1_000_002".tr, style: CustomTextStyles.displaySmallff171717)]), textAlign: TextAlign.left), Padding(padding: EdgeInsets.only(left: 2.h), child: SizedBox(height: 41.v, child: VerticalDivider(width: 2.h, thickness: 2.v, color: appTheme.gray900, endIndent: 5.h)))])), SizedBox(height: 8.v), Row(children: [Text("lbl4".tr, style: CustomTextStyles.titleMediumBluegray30018), CustomImageView(imagePath: ImageConstant.imgLayer1, height: 18.adaptSize, width: 18.adaptSize, margin: EdgeInsets.only(left: 1.h, bottom: 2.v)), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_1_0002".tr, style: CustomTextStyles.titleMediumBluegray30018))])]))), Align(alignment: Alignment.bottomLeft, child: Padding(padding: EdgeInsets.only(bottom: 7.v), child: Obx(() => Wrap(runSpacing: 6.v, spacing: 6.h, children: List<Widget>.generate(controller.settingsWalletTopUpModelObj.value.frame11ItemList.value.length, (index) {Frame11ItemModel model = controller.settingsWalletTopUpModelObj.value.frame11ItemList.value[index]; return Frame11ItemWidget(model);})))))])); } 
/// Section Widget
Widget _buildInbox() { return Padding(padding: EdgeInsets.only(right: 22.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgInbox, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(bottom: 14.v)), Expanded(child: Container(width: 294.h, margin: EdgeInsets.only(left: 10.h), child: Text("msg_effective_1st_october".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodySmallBluegray300)))])); } 
/// Section Widget
Widget _buildTop150() { return CustomElevatedButton(text: "lbl_top_150".tr, margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 54.v), onPressed: () {onTapTop150();}); } 
/// Common widget
Widget _buildDepositAmountExcl({required String depositAmountExcl, required String price, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text(depositAmountExcl, style: theme.textTheme.bodyMedium!.copyWith(color: appTheme.blueGray300))), Text(price, style: theme.textTheme.bodyMedium!.copyWith(color: appTheme.blueGray300))]); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the settingsWalletOneScreen when the action is triggered.
onTapTop150() { Get.toNamed(AppRoutes.settingsWalletOneScreen, ); } 
 }
