import 'package:social_app/widgets/custom_search_view.dart';import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_title_image.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_six.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_five.dart';import 'package:social_app/widgets/custom_outlined_button.dart';import 'package:social_app/widgets/custom_elevated_button.dart';import 'models/gaming_item_model.dart';import '../registration_stp7_screen/widgets/gaming_item_widget.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/registration_stp7_controller.dart';class RegistrationStp7Screen extends GetWidget<RegistrationStp7Controller> {const RegistrationStp7Screen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [_buildAccent(), SizedBox(height: 516.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [_buildBowling1(), _buildFiftyEight(), _buildGaming()]))])))); } 
/// Section Widget
Widget _buildAccent() { return SizedBox(height: 252.v, width: double.maxFinite, child: Stack(alignment: Alignment.topLeft, children: [CustomImageView(imagePath: ImageConstant.imgAccent14, height: 252.v, width: 154.h, alignment: Alignment.centerRight), Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 16.h, top: 91.v), child: Text("msg_what_s_your_interest".tr, style: theme.textTheme.headlineSmall))), Align(alignment: Alignment.bottomLeft, child: Container(width: 313.h, margin: EdgeInsets.only(left: 16.h, bottom: 90.v), child: Text("msg_pick_your_favorite".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.titleSmall))), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 23.v), child: CustomSearchView(width: 343.h, controller: controller.searchController, hintText: "msg_search_your_interest".tr, alignment: Alignment.bottomCenter))), CustomAppBar(height: 59.v, centerTitle: true, title: Column(children: [Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Row(children: [AppbarTitleImage(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, onTap: () {onTapArrowLeft();}), AppbarSubtitleSix(text: "lbl_step_7_of_8".tr, margin: EdgeInsets.only(left: 110.h, top: 3.v)), AppbarSubtitleFive(text: "lbl_skip".tr, margin: EdgeInsets.only(left: 105.h, top: 3.v))])), SizedBox(height: 16.v), SizedBox(height: 3.v, width: double.maxFinite, child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.center, child: SizedBox(width: double.maxFinite, child: Divider(color: appTheme.gray10001))), Align(alignment: Alignment.centerLeft, child: SizedBox(width: double.maxFinite, child: Divider(color: appTheme.green400, endIndent: 47.h)))]))]), styleType: Style.bgFill_1)])); } 
/// Section Widget
Widget _buildBowling() { return CustomOutlinedButton(width: 105.h, text: "lbl_bowling".tr, buttonStyle: CustomButtonStyles.outlineGrayTL23); } 
/// Section Widget
Widget _buildBowling1() { return Align(alignment: Alignment.bottomLeft, child: Padding(padding: EdgeInsets.only(left: 16.h, bottom: 47.v), child: Row(children: [_buildBowling(), Container(margin: EdgeInsets.only(left: 6.h), padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 10.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder23), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text("lbl_music".tr, style: theme.textTheme.titleMedium)])), Container(margin: EdgeInsets.only(left: 6.h), padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 11.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder23), child: Text("lbl_writing".tr, style: theme.textTheme.titleMedium))]))); } 
/// Section Widget
Widget _buildGymFitness() { return CustomOutlinedButton(width: 150.h, text: "msg_gym_fitness".tr, buttonStyle: CustomButtonStyles.outlineGrayTL23, onPressed: () {onTapGymFitness();}); } 
/// Section Widget
Widget _buildFashion() { return CustomOutlinedButton(width: 104.h, text: "lbl_fashion".tr, margin: EdgeInsets.only(left: 6.h), buttonStyle: CustomButtonStyles.outlineGrayTL23); } 
/// Section Widget
Widget _buildSelected() { return CustomElevatedButton(text: "lbl_0_5_selected".tr, buttonStyle: CustomButtonStyles.fillOnError, buttonTextStyle: CustomTextStyles.titleMediumGray400); } 
/// Section Widget
Widget _buildFiftyEight() { return Align(alignment: Alignment.bottomCenter, child: Container(padding: EdgeInsets.symmetric(horizontal: 16.h), decoration: AppDecoration.gradientGrayToGray, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(right: 83.h), child: Row(children: [_buildGymFitness(), _buildFashion()])), SizedBox(height: 41.v), _buildSelected(), SizedBox(height: 54.v)]))); } 
/// Section Widget
Widget _buildGaming() { return Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(top: 7.v), child: Obx(() => Wrap(runSpacing: 6.v, spacing: 6.h, children: List<Widget>.generate(controller.registrationStp7ModelObj.value.gamingItemList.value.length, (index) {GamingItemModel model = controller.registrationStp7ModelObj.value.gamingItemList.value[index]; return GamingItemWidget(model);}))))); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the registrationStep7ActiveScreen when the action is triggered.
onTapGymFitness() { Get.toNamed(AppRoutes.registrationStep7ActiveScreen, ); } 
 }
