import 'widgets/accent_item_widget.dart';import 'models/accent_item_model.dart';import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_leading_image.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_six.dart';import 'package:social_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:social_app/widgets/custom_search_view.dart';import 'package:social_app/widgets/custom_icon_button.dart';import 'widgets/arrowleft_item_widget.dart';import 'models/arrowleft_item_model.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/settings_wallet_withdraw_active_controller.dart';class SettingsWalletWithdrawActiveScreen extends GetWidget<SettingsWalletWithdrawActiveController> {const SettingsWalletWithdrawActiveScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [_buildAccent(), SizedBox(height: 14.v), Expanded(child: SingleChildScrollView(child: _buildArrowLeft()))])))); } 
/// Section Widget
Widget _buildAccent() { return SizedBox(height: 369.v, width: 359.h, child: Stack(alignment: Alignment.bottomLeft, children: [Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(bottom: 34.v), child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 1.v);}, itemCount: controller.settingsWalletWithdrawActiveModelObj.value.accentItemList.value.length, itemBuilder: (context, index) {AccentItemModel model = controller.settingsWalletWithdrawActiveModelObj.value.accentItemList.value[index]; return AccentItemWidget(model);})))), Align(alignment: Alignment.bottomLeft, child: Padding(padding: EdgeInsets.only(right: 291.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Opacity(opacity: 0.6, child: Text("lbl_today2".tr, style: CustomTextStyles.labelLargeBluegray300)), SizedBox(height: 196.v), Opacity(opacity: 0.6, child: Text("lbl_yesterday2".tr, style: CustomTextStyles.labelLargeBluegray300))]))), CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, margin: EdgeInsets.only(left: 16.h), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleSix(text: "msg_transaction_history".tr), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgLogIn, margin: EdgeInsets.symmetric(horizontal: 16.h))]), Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(top: 66.v), child: Row(children: [Expanded(child: CustomSearchView(controller: controller.searchController, hintText: "msg_search_transaction".tr)), Padding(padding: EdgeInsets.only(left: 10.h), child: CustomIconButton(height: 48.adaptSize, width: 48.adaptSize, padding: EdgeInsets.all(12.h), decoration: IconButtonStyleHelper.fillGreenTL24, child: CustomImageView(imagePath: ImageConstant.imgSettingsGray900)))])))])); } 
/// Section Widget
Widget _buildArrowLeft() { return Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 15.v);}, itemCount: controller.settingsWalletWithdrawActiveModelObj.value.arrowleftItemList.value.length, itemBuilder: (context, index) {ArrowleftItemModel model = controller.settingsWalletWithdrawActiveModelObj.value.arrowleftItemList.value[index]; return ArrowleftItemWidget(model);}))); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
