import 'package:social_app/presentation/home_page/home_page.dart';import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_leading_image.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_six.dart';import 'package:social_app/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:social_app/widgets/custom_bottom_bar.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/category_controller.dart';class CategoryScreen extends GetWidget<CategoryController> {const CategoryScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(height: 620.v, width: double.maxFinite, child: Stack(alignment: Alignment.topLeft, children: [CustomImageView(imagePath: ImageConstant.imgAccent22, height: 252.v, width: 154.h, alignment: Alignment.topRight), Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 16.h, top: 28.v, right: 32.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [_buildCelebrityOne(), SizedBox(height: 37.v), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.only(left: 20.h, right: 10.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Column(children: [CustomImageView(imagePath: ImageConstant.imgGuitar, height: 36.adaptSize, width: 36.adaptSize), SizedBox(height: 5.v), Text("lbl_musicians".tr, style: CustomTextStyles.titleSmallGray900SemiBold)]), Spacer(flex: 47), Column(children: [CustomImageView(imagePath: ImageConstant.imgMovie, height: 36.adaptSize, width: 36.adaptSize), SizedBox(height: 5.v), Text("lbl_creators".tr, style: CustomTextStyles.titleSmallGray900SemiBold)]), Spacer(flex: 52), Column(children: [CustomImageView(imagePath: ImageConstant.imgMenu, height: 36.adaptSize, width: 36.adaptSize), SizedBox(height: 5.v), Text("lbl_doctors".tr, style: CustomTextStyles.titleSmallGray900SemiBold)])]))), SizedBox(height: 60.v), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(left: 34.h, right: 2.h), child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [Column(children: [CustomImageView(imagePath: ImageConstant.imgChefHat3, height: 36.adaptSize, width: 36.adaptSize), SizedBox(height: 5.v), Text("lbl_chef".tr, style: CustomTextStyles.titleSmallGray900SemiBold)]), Spacer(flex: 56), Column(children: [CustomImageView(imagePath: ImageConstant.imgGraduateHat, height: 36.adaptSize, width: 36.adaptSize), SizedBox(height: 5.v), Text("lbl_teachers".tr, style: CustomTextStyles.titleSmallGray900SemiBold)]), Spacer(flex: 43), Column(children: [CustomImageView(imagePath: ImageConstant.imgMagicCards, height: 36.adaptSize, width: 36.adaptSize), SizedBox(height: 6.v), Text("lbl_astrologer".tr, style: CustomTextStyles.titleSmallGray900SemiBold)])]))), SizedBox(height: 59.v), CustomImageView(imagePath: ImageConstant.imgAmericanFootball, height: 36.adaptSize, width: 36.adaptSize, margin: EdgeInsets.only(left: 34.h)), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(left: 31.h), child: Text("lbl_sports".tr, style: CustomTextStyles.titleSmallGray900SemiBold))])))])), bottomNavigationBar: _buildBottomBar())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 40.v, leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, margin: EdgeInsets.only(left: 16.h, top: 8.v, bottom: 8.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleSix(text: "lbl_category".tr), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgBell02, margin: EdgeInsets.symmetric(horizontal: 16.h), onTap: () {onTapBellTwo();})]); } 
/// Section Widget
Widget _buildCelebrityOne() { return Row(children: [Container(padding: EdgeInsets.symmetric(horizontal: 30.h, vertical: 22.v), decoration: AppDecoration.outlineBlack.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgCelebrity1, height: 36.adaptSize, width: 36.adaptSize), SizedBox(height: 5.v), Text("lbl_actors".tr, style: CustomTextStyles.titleSmallGray900SemiBold)])), Spacer(flex: 42), Padding(padding: EdgeInsets.symmetric(vertical: 22.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgRunningShoe, height: 36.adaptSize, width: 36.adaptSize), SizedBox(height: 5.v), Text("lbl_athletes".tr, style: CustomTextStyles.titleSmallGray900SemiBold)])), Spacer(flex: 57), Padding(padding: EdgeInsets.symmetric(vertical: 22.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgTheater3, height: 36.adaptSize, width: 36.adaptSize), SizedBox(height: 5.v), Text("lbl_comedians".tr, style: CustomTextStyles.titleSmallGray900SemiBold)]))]); } 
/// Section Widget
Widget _buildBottomBar() { return CustomBottomBar(onChanged: (BottomBarEnum type) {Get.toNamed(getCurrentRoute(type), id: 1);}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.homePage; case BottomBarEnum.Search: return "/"; case BottomBarEnum.Message: return "/"; case BottomBarEnum.Feeds: return "/"; case BottomBarEnum.Profile: return "/"; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.homePage: return HomePage(); default: return DefaultWidget();} } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the notificationScreen when the action is triggered.
onTapBellTwo() { Get.toNamed(AppRoutes.notificationScreen, ); } 
 }
