import 'package:social_app/widgets/custom_text_form_field.dart';import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_leading_image.dart';import 'package:social_app/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/createnewpassword_controller.dart';class CreatenewpasswordScreen extends GetWidget<CreatenewpasswordController> {const CreatenewpasswordScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [_buildNewpassword(), SizedBox(height: 334.v, width: 359.h), Spacer()])), bottomNavigationBar: _buildContinue())); } 
/// Section Widget
Widget _buildInputField() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_new_password".tr, style: theme.textTheme.titleSmall), SizedBox(height: 5.v), Obx(() => CustomTextFormField(controller: controller.newpasswordController, suffix: InkWell(onTap: () {controller.isShowPassword.value = !controller.isShowPassword.value;}, child: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 15.h, 14.v), child: CustomImageView(imagePath: ImageConstant.imgEyeoff, height: 24.adaptSize, width: 24.adaptSize))), suffixConstraints: BoxConstraints(maxHeight: 52.v), obscureText: controller.isShowPassword.value))]); } 
/// Section Widget
Widget _buildInputField1() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_confirm_password".tr, style: theme.textTheme.titleSmall), SizedBox(height: 5.v), Obx(() => CustomTextFormField(controller: controller.confirmpasswordController, textInputAction: TextInputAction.done, suffix: InkWell(onTap: () {controller.isShowPassword1.value = !controller.isShowPassword1.value;}, child: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 15.h, 14.v), child: CustomImageView(imagePath: ImageConstant.imgEyeoff, height: 24.adaptSize, width: 24.adaptSize))), suffixConstraints: BoxConstraints(maxHeight: 52.v), obscureText: controller.isShowPassword1.value))]); } 
/// Section Widget
Widget _buildNewpassword() { return SizedBox(height: 334.v, width: 359.h, child: Stack(alignment: Alignment.topLeft, children: [CustomImageView(imagePath: ImageConstant.imgAccent4, height: 252.v, width: 154.h, alignment: Alignment.topRight), Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(top: 67.v), child: Text("msg_create_new_password".tr, style: theme.textTheme.headlineSmall))), Align(alignment: Alignment.topLeft, child: Container(width: 270.h, margin: EdgeInsets.only(top: 104.v), child: Text("msg_please_enter_a".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.titleSmall))), Align(alignment: Alignment.bottomLeft, child: Padding(padding: EdgeInsets.only(right: 16.h), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildInputField(), SizedBox(height: 15.v), _buildInputField1()]))), CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIcon, margin: EdgeInsets.fromLTRB(21.h, 5.v, 340.h, 5.v), onTap: () {onTapIcon();}))])); } 
/// Section Widget
Widget _buildContinue() { return CustomElevatedButton(text: "lbl_continue".tr, margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 54.v), onPressed: () {onTapContinue();}); } 

/// Navigates to the previous screen.
onTapIcon() { Get.back(); } 
/// Navigates to the forgotpasswordsuccessScreen when the action is triggered.
onTapContinue() { Get.toNamed(AppRoutes.forgotpasswordsuccessScreen, ); } 
 }
