import 'package:social_app/widgets/custom_text_form_field.dart';import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_leading_image.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_six.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/settings_verify_account_aadhaar_details_controller.dart';class SettingsVerifyAccountAadhaarDetailsScreen extends GetWidget<SettingsVerifyAccountAadhaarDetailsController> {const SettingsVerifyAccountAadhaarDetailsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [_buildFullName(), Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 3.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildInputField(email: "lbl_date_of_birth".tr, zipcode: "lbl_25_11_1992".tr), SizedBox(height: 14.v), Text("lbl_address".tr, style: theme.textTheme.titleSmall), SizedBox(height: 6.v), CustomTextFormField(controller: controller.addressController, hintText: "msg_flat_no_351_4th".tr, hintStyle: CustomTextStyles.titleMediumBluegray300), SizedBox(height: 14.v), _buildInputField4(), SizedBox(height: 15.v), _buildInputField5(), SizedBox(height: 14.v), _buildInputField(email: "lbl_pin_code".tr, zipcode: "lbl_140308".tr), SizedBox(height: 5.v)]))])))); } 
/// Section Widget
Widget _buildInputField1() { return Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(top: 75.v, right: 16.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_full_name".tr, style: theme.textTheme.titleSmall), SizedBox(height: 6.v), CustomTextFormField(controller: controller.fullNameController, hintText: "lbl_naveen_verma2".tr, hintStyle: CustomTextStyles.titleMediumBluegray300)]))); } 
/// Section Widget
Widget _buildInputField2() { return Align(alignment: Alignment.bottomLeft, child: Padding(padding: EdgeInsets.only(right: 16.h, bottom: 11.v), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_aadhaar_number".tr, style: theme.textTheme.titleSmall), SizedBox(height: 6.v), CustomTextFormField(controller: controller.youremailController, hintText: "lbl_4400_2059_9088".tr, hintStyle: CustomTextStyles.titleMediumBluegray300)]))); } 
/// Section Widget
Widget _buildFullName() { return SizedBox(height: 252.v, width: 359.h, child: Stack(alignment: Alignment.topLeft, children: [CustomImageView(imagePath: ImageConstant.imgAccent71, height: 252.v, width: 154.h, alignment: Alignment.centerRight), _buildInputField1(), _buildInputField2(), CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, margin: EdgeInsets.only(left: 16.h), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleSix(text: "lbl_aadhaar_details".tr))])); } 
/// Section Widget
Widget _buildInputField4() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_state".tr, style: theme.textTheme.titleSmall), SizedBox(height: 6.v), CustomTextFormField(controller: controller.youremailController1, hintText: "lbl_punjab".tr, hintStyle: CustomTextStyles.titleMediumBluegray300)]); } 
/// Section Widget
Widget _buildInputField5() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_city".tr, style: theme.textTheme.titleSmall), SizedBox(height: 5.v), CustomTextFormField(controller: controller.cityController, hintText: "msg_sas_nagar_mohali".tr, hintStyle: CustomTextStyles.titleMediumBluegray300, textInputAction: TextInputAction.done)]); } 
/// Common widget
Widget _buildInputField({required String email, required String zipcode, }) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(email, style: theme.textTheme.titleSmall!.copyWith(color: appTheme.blueGray300)), SizedBox(height: 6.v), Container(padding: EdgeInsets.all(14.h), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(children: [Text(zipcode, style: CustomTextStyles.titleMediumBluegray300.copyWith(color: appTheme.blueGray300))]))]); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
