import 'package:social_app/widgets/custom_icon_button.dart';import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_leading_image.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_six.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/setting_account_settings_controller.dart';class SettingAccountSettingsScreen extends GetWidget<SettingAccountSettingsController> {const SettingAccountSettingsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 451.v, width: 359.h, child: Stack(alignment: Alignment.bottomLeft, children: [CustomImageView(imagePath: ImageConstant.imgAccent41, height: 252.v, width: 154.h, alignment: Alignment.topRight), _buildUsername1(), _buildAppBar()])), Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: _buildCreditCard(creditCard: ImageConstant.imgVerifiedUser2, gender: "lbl_change_password".tr, onTapCreditCard1: () {onTapVerifiedUserTwo();}))])))); } 
/// Section Widget
Widget _buildUsername1() { return Align(alignment: Alignment.bottomLeft, child: Container(margin: EdgeInsets.only(right: 16.h), decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildVerifiedUserTwo(changePhoneNumber: "lbl_username".tr, onTapVerifiedUserTwo1: () {onTapUsername();}), _buildCreditCard(creditCard: ImageConstant.imgCalendarDeepPurple300, gender: "lbl_birthday".tr), _buildCreditCard(creditCard: ImageConstant.imgCreditCard, gender: "lbl_gender".tr, onTapCreditCard1: () {onTapCreditCard();}), _buildCreditCard(creditCard: ImageConstant.imgVideoYellow900, gender: "lbl_change_email".tr), _buildVerifiedUserTwo(changePhoneNumber: "msg_change_phone_number".tr)]))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, margin: EdgeInsets.only(left: 16.h), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleSix(text: "msg_account_settings".tr)); } 
/// Common widget
Widget _buildCreditCard({required String creditCard, required String gender, Function? onTapCreditCard1, }) { return GestureDetector(onTap: () {onTapCreditCard1!.call();}, child: Container(padding: EdgeInsets.fromLTRB(15.h, 16.v, 15.h, 15.v), decoration: AppDecoration.outlineGray300011, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: 44.adaptSize, width: 44.adaptSize, padding: EdgeInsets.all(10.h), decoration: AppDecoration.fillGreen400.copyWith(borderRadius: BorderRadiusStyle.circleBorder23), child: CustomImageView(imagePath: creditCard, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 15.h, top: 12.v, bottom: 11.v), child: Text(gender, style: theme.textTheme.titleMedium!.copyWith(color: appTheme.gray900))), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 10.v))]))); } 
/// Common widget
Widget _buildVerifiedUserTwo({required String changePhoneNumber, Function? onTapVerifiedUserTwo1, }) { return GestureDetector(onTap: () {onTapVerifiedUserTwo1!.call();}, child: Container(padding: EdgeInsets.fromLTRB(15.h, 16.v, 15.h, 15.v), decoration: AppDecoration.outlineGray300011, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomIconButton(height: 44.adaptSize, width: 44.adaptSize, padding: EdgeInsets.all(10.h), decoration: IconButtonStyleHelper.fillGrayTL22, child: CustomImageView(imagePath: ImageConstant.imgVerifiedUser2)), Padding(padding: EdgeInsets.only(left: 15.h, top: 13.v, bottom: 10.v), child: Text(changePhoneNumber, style: theme.textTheme.titleMedium!.copyWith(color: appTheme.gray900))), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 10.v))]))); } 
/// Navigates to the settingAccountSettingsUserNameScreen when the action is triggered.
onTapUsername() { Get.toNamed(AppRoutes.settingAccountSettingsUserNameScreen, ); } 
/// Navigates to the settingAccountSettingsChangeGenderScreen when the action is triggered.
onTapCreditCard() { Get.toNamed(AppRoutes.settingAccountSettingsChangeGenderScreen, ); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the settingAccountSettingsChangePasswordScreen when the action is triggered.
onTapVerifiedUserTwo() { Get.toNamed(AppRoutes.settingAccountSettingsChangePasswordScreen, ); } 
 }
