import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_leading_image.dart';import 'package:social_app/widgets/custom_icon_button.dart';import 'package:social_app/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/setting_account_settings_change_gender_controller.dart';class SettingAccountSettingsChangeGenderScreen extends GetWidget<SettingAccountSettingsChangeGenderController> {const SettingAccountSettingsChangeGenderScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildAccent(), SizedBox(height: 313.v, width: 359.h), Spacer()])), bottomNavigationBar: _buildSave())); } 
/// Section Widget
Widget _buildAccent() { return SizedBox(height: 313.v, width: 359.h, child: Stack(alignment: Alignment.topLeft, children: [CustomImageView(imagePath: ImageConstant.imgAccent44, height: 252.v, width: 154.h, alignment: Alignment.topRight), Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(top: 16.v, right: 193.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIcon, margin: EdgeInsets.fromLTRB(21.h, 5.v, 340.h, 5.v), onTap: () {onTapIcon();})), SizedBox(height: 28.v), Align(alignment: Alignment.center, child: Text("lbl_change_gender".tr, style: theme.textTheme.headlineSmall))]))), Align(alignment: Alignment.topLeft, child: Container(width: 323.h, margin: EdgeInsets.only(top: 104.v), child: Text("msg_this_help_us_find".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.titleSmall))), Align(alignment: Alignment.bottomLeft, child: Container(margin: EdgeInsets.only(right: 195.h), padding: EdgeInsets.symmetric(horizontal: 51.h, vertical: 27.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomIconButton(height: 60.adaptSize, width: 60.adaptSize, padding: EdgeInsets.all(12.h), decoration: IconButtonStyleHelper.fillGray, child: CustomImageView(imagePath: ImageConstant.imgIconBlueGray30060x60)), SizedBox(height: 5.v), Text("lbl_male".tr, style: CustomTextStyles.titleMediumBluegray300)]))), Align(alignment: Alignment.bottomRight, child: Container(margin: EdgeInsets.only(left: 180.h, right: 16.h), padding: EdgeInsets.symmetric(horizontal: 50.h, vertical: 25.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomIconButton(height: 60.adaptSize, width: 60.adaptSize, padding: EdgeInsets.all(12.h), decoration: IconButtonStyleHelper.fillGray, child: CustomImageView(imagePath: ImageConstant.imgIconBlueGray300)), SizedBox(height: 9.v), Text("lbl_female".tr, style: CustomTextStyles.titleMediumBluegray300)])))])); } 
/// Section Widget
Widget _buildSave() { return CustomElevatedButton(text: "lbl_save".tr, margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 54.v), onPressed: () {onTapSave();}); } 

/// Navigates to the previous screen.
onTapIcon() { Get.back(); } 
/// Navigates to the settingAccountSettingsScreen when the action is triggered.
onTapSave() { Get.toNamed(AppRoutes.settingAccountSettingsScreen, ); } 
 }
