import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_leading_image.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_six.dart';import 'package:social_app/widgets/custom_text_form_field.dart';import 'package:social_app/core/utils/validation_functions.dart';import 'models/dancingsinging4_item_model.dart';import '../setting_edit_profile_screen/widgets/dancingsinging4_item_widget.dart';import 'package:social_app/widgets/custom_outlined_button.dart';import 'package:social_app/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/setting_edit_profile_controller.dart';
// ignore_for_file: must_be_immutable
class SettingEditProfileScreen extends GetWidget<SettingEditProfileController> {SettingEditProfileScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Form(key: _formKey, child: SingleChildScrollView(child: Container(height: 934.v, width: 359.h, margin: EdgeInsets.only(left: 16.h, bottom: 54.v), child: Stack(alignment: Alignment.bottomLeft, children: [CustomImageView(imagePath: ImageConstant.imgAccent38, height: 252.v, width: 154.h, alignment: Alignment.topRight), Align(alignment: Alignment.bottomLeft, child: Padding(padding: EdgeInsets.only(right: 16.h), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildInputField(), SizedBox(height: 14.v), _buildInputField1(), SizedBox(height: 14.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_bio2".tr, style: theme.textTheme.titleSmall)), SizedBox(height: 6.v), CustomTextFormField(controller: controller.descriptionController, hintText: "msg_hello_i_am_an2".tr, textInputAction: TextInputAction.done, textInputType: TextInputType.phone, validator: (value) {if (!isValidPhone(value)) {return "err_msg_please_enter_valid_phone_number".tr;} return null;}, maxLines: 6, contentPadding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 10.v)), SizedBox(height: 6.v), Align(alignment: Alignment.centerRight, child: RichText(text: TextSpan(children: [TextSpan(text: "lbl_400".tr, style: CustomTextStyles.labelLargeff171717), TextSpan(text: "lbl_500".tr, style: CustomTextStyles.labelLargeff95a4b7)]), textAlign: TextAlign.left)), SizedBox(height: 13.v), _buildMyOccupation(myOccupation: "lbl_my_interests".tr, edit: "lbl_edit".tr, onTapEdit: () {onTapTxtEdit();}), SizedBox(height: 9.v), _buildDancingSinging(), SizedBox(height: 14.v), _buildMyOccupation(myOccupation: "lbl_my_occupation".tr, edit: "lbl_edit".tr, onTapEdit: () {onTapTxtEdit1();}), SizedBox(height: 9.v), CustomOutlinedButton(width: 138.h, text: "lbl_ux_ui_designer".tr, buttonStyle: CustomButtonStyles.outlineGrayTL23, alignment: Alignment.centerLeft), SizedBox(height: 30.v), CustomElevatedButton(text: "lbl_save_changes".tr, onPressed: () {onTapSaveChanges();})]))), CustomImageView(imagePath: ImageConstant.imgFrame31, height: 100.adaptSize, width: 100.adaptSize, radius: BorderRadius.circular(50.h), alignment: Alignment.topLeft, margin: EdgeInsets.only(left: 121.h, top: 71.v)), Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 105.h, top: 191.v), child: Text("msg_change_profile_picture".tr, style: theme.textTheme.titleSmall)))])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, margin: EdgeInsets.only(left: 16.h), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleSix(text: "lbl_edit_profile".tr)); } 
/// Section Widget
Widget _buildInputField() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_first_name".tr, style: theme.textTheme.titleSmall), SizedBox(height: 6.v), CustomTextFormField(controller: controller.firstNameController, hintText: "lbl_naveen".tr)]); } 
/// Section Widget
Widget _buildInputField1() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_last_name".tr, style: theme.textTheme.titleSmall), SizedBox(height: 6.v), CustomTextFormField(controller: controller.lastNameController, hintText: "lbl_verma".tr)]); } 
/// Section Widget
Widget _buildDancingSinging() { return Obx(() => Wrap(runSpacing: 6.v, spacing: 6.h, children: List<Widget>.generate(controller.settingEditProfileModelObj.value.dancingsinging4ItemList.value.length, (index) {Dancingsinging4ItemModel model = controller.settingEditProfileModelObj.value.dancingsinging4ItemList.value[index]; return Dancingsinging4ItemWidget(model);}))); } 
/// Common widget
Widget _buildMyOccupation({required String myOccupation, required String edit, Function? onTapEdit, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text(myOccupation, style: theme.textTheme.titleSmall!.copyWith(color: appTheme.blueGray300))), GestureDetector(onTap: () {onTapEdit!.call();}, child: Text(edit, style: CustomTextStyles.titleSmallDeeporangeA200.copyWith(color: appTheme.deepOrangeA200)))]); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the settingEditProfileInterestsScreen when the action is triggered.
onTapTxtEdit() { Get.toNamed(AppRoutes.settingEditProfileInterestsScreen, ); } 
/// Navigates to the settingEditProfileProfessionScreen when the action is triggered.
onTapTxtEdit1() { Get.toNamed(AppRoutes.settingEditProfileProfessionScreen, ); } 
/// Navigates to the settingScreen when the action is triggered.
onTapSaveChanges() { Get.toNamed(AppRoutes.settingScreen, ); } 
 }
