import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_leading_image.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_three.dart';import 'package:social_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:social_app/widgets/custom_icon_button.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/video_call_one_controller.dart';import 'package:social_app/presentation/send_gift_bottomsheet/send_gift_bottomsheet.dart';import 'package:social_app/presentation/send_gift_bottomsheet/controller/send_gift_controller.dart';class VideoCallOneScreen extends GetWidget<VideoCallOneController> {const VideoCallOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, backgroundColor: appTheme.gray900, appBar: _buildAppBar(), body: Container(width: SizeUtils.width, height: SizeUtils.height, padding: EdgeInsets.only(top: 24.v), decoration: BoxDecoration(color: appTheme.gray900, image: DecorationImage(image: AssetImage(ImageConstant.imgVideoCallOne), fit: BoxFit.cover)), child: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 36.v), CustomImageView(imagePath: ImageConstant.imgMaskGroup122x91, height: 122.v, width: 91.h, alignment: Alignment.centerRight, margin: EdgeInsets.only(right: 16.h)), Spacer(), _buildThirtyOne()]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimarycontainer, margin: EdgeInsets.only(left: 16.h), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleThree(text: "msg_end_to_end_encrypted".tr), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgVolumeUpFill0, margin: EdgeInsets.symmetric(horizontal: 16.h))]); } 
/// Section Widget
Widget _buildThirtyOne() { return Container(padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 15.v), decoration: AppDecoration.gradientBlackToBlack90001, child: Column(children: [Text("lbl_anjali_arora".tr, style: CustomTextStyles.titleLargeOnPrimaryContainer), SizedBox(height: 8.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: 7.adaptSize, width: 7.adaptSize, margin: EdgeInsets.only(top: 5.v, bottom: 4.v), decoration: BoxDecoration(color: appTheme.deepOrange50001, borderRadius: BorderRadius.circular(3.h), border: Border.all(color: theme.colorScheme.onPrimaryContainer.withOpacity(1), width: 1.h))), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_00_05_24".tr, style: CustomTextStyles.titleSmallOnPrimaryContainer))]), SizedBox(height: 30.v), Padding(padding: EdgeInsets.only(left: 1.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(right: 8.h), child: CustomIconButton(height: 52.adaptSize, width: 52.adaptSize, padding: EdgeInsets.all(14.h), decoration: IconButtonStyleHelper.fillOnPrimaryContainer, child: CustomImageView(imagePath: ImageConstant.imgFlipCameraIos)))), Expanded(child: Padding(padding: EdgeInsets.symmetric(horizontal: 8.h), child: CustomIconButton(height: 52.adaptSize, width: 52.adaptSize, padding: EdgeInsets.all(14.h), decoration: IconButtonStyleHelper.fillOnPrimaryContainer, child: CustomImageView(imagePath: ImageConstant.imgMicOffFill0W)))), Expanded(child: Padding(padding: EdgeInsets.symmetric(horizontal: 8.h), child: CustomIconButton(height: 52.adaptSize, width: 52.adaptSize, padding: EdgeInsets.all(12.h), decoration: IconButtonStyleHelper.fillPrimaryContainer, onTap: () {onTapBtnEndCall();}, child: CustomImageView(imagePath: ImageConstant.imgEndCall)))), Expanded(child: Padding(padding: EdgeInsets.symmetric(horizontal: 8.h), child: CustomIconButton(height: 52.adaptSize, width: 52.adaptSize, child: CustomImageView()))), Expanded(child: Padding(padding: EdgeInsets.only(left: 8.h), child: CustomIconButton(height: 52.adaptSize, width: 52.adaptSize, padding: EdgeInsets.all(14.h), decoration: IconButtonStyleHelper.fillOnPrimaryContainer, onTap: () {onTapBtnMoreHorizontal();}, child: CustomImageView(imagePath: ImageConstant.imgMoreHorizontal))))])), SizedBox(height: 38.v)])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the giveRatingScreen when the action is triggered.
onTapBtnEndCall() { Get.toNamed(AppRoutes.giveRatingScreen, ); } 

/// Displays a scrollable bottom sheet widget using the [Get] package 
/// and the [SendGiftBottomsheet] widget.
///
/// The bottom sheet is controlled by the [SendGiftController]
/// and is displayed using the [Get.bottomSheet] method with
/// [isScrollControlled] set to true.

onTapBtnMoreHorizontal() { Get.bottomSheet(SendGiftBottomsheet(Get.put(SendGiftController(),),),isScrollControlled: true,); } 
 }
