import 'package:social_app/widgets/app_bar/custom_app_bar.dart';import 'package:social_app/widgets/app_bar/appbar_leading_image.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_three.dart';import 'package:social_app/widgets/app_bar/appbar_subtitle_two.dart';import 'widgets/newpostchoosepostimage_item_widget.dart';import 'models/newpostchoosepostimage_item_model.dart';import 'package:flutter/material.dart';import 'package:social_app/core/app_export.dart';import 'controller/new_post_choose_post_image_controller.dart';class NewPostChoosePostImageScreen extends GetWidget<NewPostChoosePostImageController> {const NewPostChoosePostImageScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: appTheme.gray900, appBar: _buildAppBar(), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 16.v), CustomImageView(imagePath: ImageConstant.imgRectangle25244375x375, height: 375.adaptSize, width: 375.adaptSize), _buildNewPostChoosepostimage()])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowRightOnprimarycontainer, margin: EdgeInsets.only(left: 16.h), onTap: () {onTapArrowRight();}), centerTitle: true, title: AppbarSubtitleThree(text: "lbl_new_post2".tr), actions: [AppbarSubtitleTwo(text: "lbl_next".tr, margin: EdgeInsets.fromLTRB(16.h, 2.v, 16.h, 1.v), onTap: () {onTapNext();})]); } 
/// Section Widget
Widget _buildNewPostChoosepostimage() { return Obx(() => GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 57.v, crossAxisCount: 1, mainAxisSpacing: 1.h, crossAxisSpacing: 1.h), physics: NeverScrollableScrollPhysics(), itemCount: controller.newPostChoosePostImageModelObj.value.newpostchoosepostimageItemList.value.length, itemBuilder: (context, index) {NewpostchoosepostimageItemModel model = controller.newPostChoosePostImageModelObj.value.newpostchoosepostimageItemList.value[index]; return NewpostchoosepostimageItemWidget(model);})); } 
/// Navigates to the myProfilePostsTabContainerScreen when the action is triggered.
onTapArrowRight() { Get.toNamed(AppRoutes.myProfilePostsTabContainerScreen, ); } 
/// Navigates to the followingScreen when the action is triggered.
onTapNext() { Get.toNamed(AppRoutes.followingScreen, ); } 
 }
